package com.service.backend.shared.constants;

public enum ErrorCode {
    RESOURCES_DUPLICATE,
    INVALID_PASSWORD,
    USER_NOT_FOUND,

    RESOURCES_NOT_FOUND,
    FORBIDDEN,

    // Event modular
    EVENT_NOT_FOUND,
    TICKET_NOT_FOUND,
    EVENT_FULLY_BOOKED,
    ALREADY_INTERESTED,
    TICKET_ALREADY_CANCELLED,
    TICKET_ALREADY_CHECKED_IN,

    // Article module
    NEWS_NOT_FOUND,
    JOB_NOT_FOUND,
    LEARNING_RESOURCE_NOT_FOUND,
    ACHIEVEMENT_NOT_FOUND,
    ITEM_ALREADY_SAVED,
    SAVED_ITEM_NOT_FOUND,

    // Mentorship modulee
    MENTOR_PROFILE_NOT_FOUND,
    MENTOR_PROFILE_ALREADY_EXISTS,
    EXPERTISE_NOT_FOUND,
    AVAILABILITY_NOT_FOUND,
    AVAILABILITY_NOT_AVAILABLE,
    SESSION_NOT_FOUND,
    SESSION_ALREADY_CANCELLED,
    SESSION_NOT_COMPLETED,
    FEEDBACK_ALREADY_EXISTS,
}
