services:
  db:
    image: postgres:15-alpine
    container_name: db
    restart: unless-stopped

    environment:
      POSTGRES_DB: db
      POSTGRES_USER: user
      POSTGRES_PASSWORD: 123

    ports:
      - "5433:5432"

    volumes:
      - db_data:/var/lib/postgresql/data
      - ./docs/postgre.sql:/docker-entrypoint-initdb.d/01-init.sql
      - ./docs/sample.sql:/docker-entrypoint-initdb.d/02-sample.sql

    networks:
      - backend

networks:
  backend:
    driver: bridge

volumes:
  db_data:
