services:
  db:
    image: postgres:15-alpine
    container_name: db
    restart: unless-stopped
    environment:
      POSTGRES_DB: db
      POSTGRES_USER: user
      POSTGRES_PASSWORD: 123
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
      - ./init_script.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - backend

networks:
  backend:
    driver: bridge

volumes:
  db_data:
