package com.service.backend.article.dto;

import lombok.AllArgsConstructor;
import lombok.Data;
import lombok.NoArgsConstructor;
import org.springframework.data.relational.core.mapping.Column;

import java.time.LocalDateTime;

/**
 * Class-based R2DBC projection for public news lists.
 *
 * The content column is generated by SQL as a bounded plain-text preview. Detail
 * endpoints intentionally continue using {@link NewsResponse} and full content.
 */
@Data
@NoArgsConstructor
@AllArgsConstructor
public class NewsListItemResponse {

    @Column("id")
    private Integer id;

    @Column("organization_id")
    private Integer organizationId;

    @Column("author_member_id")
    private Integer authorMemberId;

    @Column("title")
    private String title;

    @Column("slug")
    private String slug;

    @Column("content")
    private String content;

    @Column("thumbnail_url")
    private String thumbnailUrl;

    @Column("topic")
    private String topic;

    @Column("url")
    private String url;

    @Column("is_hidden")
    private Boolean isHidden;

    @Column("created_at")
    private LocalDateTime createdAt;

    @Column("updated_at")
    private LocalDateTime updatedAt;
}
