-- Mentorship schema fixes discovered during E2E testing (2026-06).
-- These columns/tables are referenced by the backend entities & queries but
-- were missing from older live databases, causing silent failures:
--   * mentor/mentee cancel + mentor postpone -> 500 (missing cancel_reason)
--   * every notification save failed silently (missing notifications.link)
--   * report mentor/mentee -> 500 (missing mentorship_reports table)
--
-- Apply: docker exec -i db psql -U user -d db < docs/mentorship/migration-session-cancel-report-notif.sql

ALTER TABLE mentorship_sessions ADD COLUMN IF NOT EXISTS cancel_reason text;

ALTER TABLE notifications ADD COLUMN IF NOT EXISTS link text;

CREATE TABLE IF NOT EXISTS mentorship_reports (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  session_id integer REFERENCES mentorship_sessions(id),
  reporter_member_id integer REFERENCES organization_members(user_id),
  reported_member_id integer REFERENCES organization_members(user_id),
  reason_category text,
  description text,
  status text,
  created_at timestamp
);
