--
-- PostgreSQL database dump
--


-- Dumped from database version 16.14 (Ubuntu 16.14-0ubuntu0.24.04.1)
-- Dumped by pg_dump version 16.14

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

--
-- Name: pg_trgm; Type: EXTENSION; Schema: -; Owner: -
--

CREATE EXTENSION IF NOT EXISTS pg_trgm WITH SCHEMA public;


SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- Name: achievements; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.achievements (
    id integer NOT NULL,
    member_id integer,
    title text,
    description text,
    image_url text,
    awarded_date date,
    topic text,
    status text,
    created_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
    updated_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
    url text
);


--
-- Name: achievements_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.achievements ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.achievements_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: admin_audit_logs; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.admin_audit_logs (
    id bigint NOT NULL,
    admin_user_id integer NOT NULL,
    target_user_id integer,
    action text NOT NULL,
    resource_type text NOT NULL,
    resource_id text,
    before_data jsonb,
    after_data jsonb,
    metadata jsonb,
    created_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
    http_method text,
    request_path text,
    ip_address text,
    user_agent text,
    status_code integer,
    latency_ms bigint,
    status text,
    admin_role text
);


--
-- Name: admin_audit_logs_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

CREATE SEQUENCE public.admin_audit_logs_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


--
-- Name: admin_audit_logs_id_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: -
--

ALTER SEQUENCE public.admin_audit_logs_id_seq OWNED BY public.admin_audit_logs.id;


--
-- Name: ai_models; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.ai_models (
    id integer NOT NULL,
    provider_id integer NOT NULL,
    model_name text NOT NULL,
    priority integer DEFAULT 0 NOT NULL,
    enabled boolean DEFAULT true NOT NULL,
    created_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
    updated_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP
);


--
-- Name: ai_models_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.ai_models ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.ai_models_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: ai_providers; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.ai_providers (
    id integer NOT NULL,
    name text NOT NULL,
    provider_type text DEFAULT 'openai_compatible'::text NOT NULL,
    base_url text,
    api_key_enc text,
    enabled boolean DEFAULT true NOT NULL,
    priority integer DEFAULT 0 NOT NULL,
    created_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
    updated_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP
);


--
-- Name: ai_providers_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.ai_providers ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.ai_providers_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: alumni_posts; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.alumni_posts (
    id integer NOT NULL,
    organization_id integer,
    author_member_id integer,
    title text,
    slug text,
    content text,
    thumbnail_url text,
    topic text,
    url text,
    is_hidden boolean,
    published_at timestamp without time zone,
    created_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
    updated_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP
);


--
-- Name: alumni_posts_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.alumni_posts ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.alumni_posts_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: chat_conversation_requests; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.chat_conversation_requests (
    id bigint NOT NULL,
    member_low_id integer NOT NULL,
    member_high_id integer NOT NULL,
    requester_member_id integer NOT NULL,
    target_member_id integer NOT NULL,
    chat_group_id integer NOT NULL,
    last_request_message_id integer NOT NULL,
    cooldown_until timestamp without time zone,
    status text DEFAULT 'PENDING'::text NOT NULL,
    created_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
    updated_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP
);


--
-- Name: chat_conversation_requests_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

CREATE SEQUENCE public.chat_conversation_requests_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


--
-- Name: chat_conversation_requests_id_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: -
--

ALTER SEQUENCE public.chat_conversation_requests_id_seq OWNED BY public.chat_conversation_requests.id;


--
-- Name: chat_group_members; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.chat_group_members (
    id integer NOT NULL,
    group_id integer NOT NULL,
    member_id integer NOT NULL,
    role text DEFAULT 'MEMBER'::text,
    joined_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP
);


--
-- Name: chat_group_members_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.chat_group_members ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.chat_group_members_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: chat_groups; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.chat_groups (
    id integer NOT NULL,
    type text NOT NULL,
    title text,
    created_by integer NOT NULL,
    created_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
    updated_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
    avatar_url text
);


--
-- Name: chat_groups_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.chat_groups ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.chat_groups_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: chat_messages; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.chat_messages (
    id integer NOT NULL,
    group_id integer NOT NULL,
    sender_member_id integer NOT NULL,
    content text NOT NULL,
    message_type text DEFAULT 'TEXT'::text,
    metadata jsonb,
    created_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
    edited_at timestamp without time zone,
    deleted_at timestamp without time zone
);


--
-- Name: chat_messages_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.chat_messages ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.chat_messages_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: device_tokens; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.device_tokens (
    id integer NOT NULL,
    user_id integer NOT NULL,
    fcm_token text NOT NULL,
    platform text,
    created_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
    updated_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP
);


--
-- Name: device_tokens_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.device_tokens ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.device_tokens_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: education_change_requests; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.education_change_requests (
    id integer NOT NULL,
    member_id integer NOT NULL,
    organization_id integer NOT NULL,
    old_data text,
    new_data text NOT NULL,
    status text DEFAULT 'PENDING'::text NOT NULL,
    admin_note text,
    reviewed_by_user_id integer,
    created_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
    reviewed_at timestamp without time zone
);


--
-- Name: education_change_requests_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.education_change_requests ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.education_change_requests_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: email_templates; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.email_templates (
    id bigint NOT NULL,
    template_code character varying(100) NOT NULL,
    subject text,
    content text,
    description text,
    variables text DEFAULT '[]'::text,
    updated_by bigint,
    updated_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP
);


--
-- Name: email_templates_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

CREATE SEQUENCE public.email_templates_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


--
-- Name: email_templates_id_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: -
--

ALTER SEQUENCE public.email_templates_id_seq OWNED BY public.email_templates.id;


--
-- Name: event_email_logs; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.event_email_logs (
    id integer NOT NULL,
    event_id integer NOT NULL,
    sent_by integer NOT NULL,
    template_name text,
    subject text,
    recipient_count integer DEFAULT 0,
    sent_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP
);


--
-- Name: event_email_logs_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.event_email_logs ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.event_email_logs_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: event_interests; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.event_interests (
    id integer NOT NULL,
    event_id integer,
    member_id integer,
    created_at timestamp without time zone
);


--
-- Name: event_interests_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.event_interests ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.event_interests_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: event_invitations; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.event_invitations (
    id integer NOT NULL,
    event_id integer NOT NULL,
    member_id integer,
    email text NOT NULL,
    token text NOT NULL,
    status text DEFAULT 'PENDING'::text NOT NULL,
    invited_by integer NOT NULL,
    invited_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
    confirmed_at timestamp without time zone,
    expires_at timestamp without time zone
);


--
-- Name: event_invitations_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.event_invitations ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.event_invitations_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: event_questions; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.event_questions (
    id integer NOT NULL,
    event_id integer NOT NULL,
    type text NOT NULL,
    label text NOT NULL,
    options text,
    required boolean DEFAULT false NOT NULL,
    order_index integer DEFAULT 0 NOT NULL,
    created_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP
);


--
-- Name: event_questions_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.event_questions ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.event_questions_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: event_tickets; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.event_tickets (
    id integer NOT NULL,
    event_id integer,
    member_id integer,
    guest_name text,
    guest_email text,
    guest_phone text,
    ticket_code text,
    status text DEFAULT 'ISSUED'::text NOT NULL,
    registered_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
    checked_in_at timestamp without time zone,
    reviewed_by integer,
    reviewed_at timestamp without time zone,
    reject_reason text,
    registration_answers text,
    cancel_reason text
);


--
-- Name: event_tickets_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.event_tickets ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.event_tickets_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: events; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.events (
    id integer NOT NULL,
    organization_id integer,
    creator_member_id integer,
    title text,
    description text,
    banner_url text,
    location text,
    start_time timestamp without time zone,
    end_time timestamp without time zone,
    registration_start_at timestamp without time zone,
    registration_end_at timestamp without time zone,
    max_capacity integer,
    interested_count integer DEFAULT 0,
    topic text,
    is_published boolean DEFAULT false,
    created_at timestamp without time zone,
    updated_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
    requires_check_in boolean DEFAULT false NOT NULL
);


--
-- Name: events_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.events ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.events_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: forum_categories; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.forum_categories (
    id integer NOT NULL,
    parent_id integer,
    organization_id integer,
    name text,
    description text,
    created_at timestamp without time zone,
    updated_at timestamp without time zone,
    status text DEFAULT 'ACTIVE'::text
);


--
-- Name: forum_categories_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.forum_categories ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.forum_categories_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: forum_post_reactions; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.forum_post_reactions (
    id integer NOT NULL,
    post_id integer NOT NULL,
    member_id integer NOT NULL,
    created_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP
);


--
-- Name: forum_post_reactions_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.forum_post_reactions ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.forum_post_reactions_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: forum_post_reports; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.forum_post_reports (
    id bigint NOT NULL,
    post_id integer NOT NULL,
    reporter_member_id integer NOT NULL,
    reason text,
    status text DEFAULT 'PENDING'::text,
    reviewed_by_user_id integer,
    review_note text,
    created_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
    updated_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP
);


--
-- Name: forum_post_reports_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

CREATE SEQUENCE public.forum_post_reports_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


--
-- Name: forum_post_reports_id_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: -
--

ALTER SEQUENCE public.forum_post_reports_id_seq OWNED BY public.forum_post_reports.id;


--
-- Name: forum_posts; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.forum_posts (
    id integer NOT NULL,
    topic_id integer,
    author_member_id integer,
    content text,
    answer_to_post_id integer,
    ai_tag text,
    is_banned boolean DEFAULT false,
    is_hidden boolean DEFAULT false,
    created_at timestamp without time zone,
    updated_at timestamp without time zone
);


--
-- Name: forum_posts_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.forum_posts ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.forum_posts_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: forum_topic_subscriptions; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.forum_topic_subscriptions (
    id integer NOT NULL,
    topic_id integer NOT NULL,
    member_id integer NOT NULL,
    last_read_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
    last_notified_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
    created_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP
);


--
-- Name: forum_topic_subscriptions_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.forum_topic_subscriptions ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.forum_topic_subscriptions_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: forum_topics; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.forum_topics (
    id integer NOT NULL,
    organization_id integer,
    title text,
    created_by_member_id integer,
    category_id integer,
    view_count integer DEFAULT 0,
    created_at timestamp without time zone,
    updated_at timestamp without time zone,
    status text DEFAULT 'ACTIVE'::text
);


--
-- Name: forum_topics_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.forum_topics ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.forum_topics_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: fund_donations; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.fund_donations (
    id bigint NOT NULL,
    fund_id integer,
    donor_member_id integer,
    donor_name text,
    amount numeric NOT NULL,
    address text,
    phone text,
    email text,
    message text,
    status text,
    created_at timestamp without time zone
);


--
-- Name: fund_donations_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

CREATE SEQUENCE public.fund_donations_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


--
-- Name: fund_donations_id_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: -
--

ALTER SEQUENCE public.fund_donations_id_seq OWNED BY public.fund_donations.id;


--
-- Name: fund_receiving_infos; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.fund_receiving_infos (
    id bigint NOT NULL,
    account_number text,
    account_name text,
    bank_name text,
    is_active boolean
);


--
-- Name: fund_receiving_infos_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

CREATE SEQUENCE public.fund_receiving_infos_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


--
-- Name: fund_receiving_infos_id_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: -
--

ALTER SEQUENCE public.fund_receiving_infos_id_seq OWNED BY public.fund_receiving_infos.id;


--
-- Name: funds; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.funds (
    id bigint NOT NULL,
    organization_id integer,
    manager_name text,
    name text,
    logo_url text,
    fund_receiving_info_id integer,
    description_short text,
    description_full text,
    target_amount numeric,
    current_amount numeric,
    time_started timestamp without time zone,
    donor_count integer DEFAULT 0,
    topic text,
    time_ended timestamp without time zone,
    created_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
    updated_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
    manager_email text NOT NULL,
    fund_document_url text,
    donation_list_public boolean DEFAULT false NOT NULL
);


--
-- Name: funds_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

CREATE SEQUENCE public.funds_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


--
-- Name: funds_id_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: -
--

ALTER SEQUENCE public.funds_id_seq OWNED BY public.funds.id;


--
-- Name: jobs; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.jobs (
    id integer NOT NULL,
    organization_id integer,
    poster_member_id integer,
    is_referral boolean DEFAULT false,
    type text,
    title text,
    company_name text,
    location text,
    salary_range text,
    description text,
    how_to_apply text,
    deadline date,
    is_active boolean,
    created_at timestamp without time zone,
    updated_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
    url text
);


--
-- Name: jobs_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.jobs ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.jobs_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: learning_resources; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.learning_resources (
    id integer NOT NULL,
    organization_id integer,
    uploader_member_id integer,
    title text,
    type text,
    link_url text,
    description text,
    created_at timestamp without time zone,
    updated_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
    thumbnail_url text,
    status text DEFAULT 'APPROVED'::text NOT NULL,
    CONSTRAINT learning_resources_status_check CHECK ((status = ANY (ARRAY['PENDING'::text, 'APPROVED'::text, 'REJECTED'::text])))
);


--
-- Name: learning_resources_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.learning_resources ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.learning_resources_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: mentee_profiles; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.mentee_profiles (
    member_id integer NOT NULL,
    mentoring_goal text,
    major text,
    academic_year text,
    interests text,
    is_active boolean DEFAULT true NOT NULL,
    created_at timestamp without time zone,
    updated_at timestamp without time zone
);


--
-- Name: mentor_availabilities; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.mentor_availabilities (
    id integer NOT NULL,
    mentor_member_id integer,
    start_time timestamp without time zone,
    end_time timestamp without time zone,
    status text DEFAULT 'AVAILABLE'::text
);


--
-- Name: mentor_availabilities_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.mentor_availabilities ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.mentor_availabilities_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: mentor_expertise; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.mentor_expertise (
    id integer NOT NULL,
    mentor_member_id integer,
    topic text,
    years_experience integer,
    description text,
    category text,
    tag text
);


--
-- Name: mentor_expertise_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.mentor_expertise ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.mentor_expertise_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: mentor_profiles; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.mentor_profiles (
    member_id integer NOT NULL,
    current_job_title text,
    current_company text,
    bio text,
    rating_avg numeric DEFAULT 0,
    total_sessions integer DEFAULT 0,
    status text DEFAULT 'DRAFT'::text NOT NULL,
    review_note text,
    reviewed_at timestamp without time zone,
    reviewed_by integer,
    default_meeting_link text,
    booking_window_settings text,
    extended_profile text,
    created_at timestamp without time zone,
    updated_at timestamp without time zone,
    CONSTRAINT mentor_profiles_status_check CHECK ((status = ANY (ARRAY['DRAFT'::text, 'PENDING'::text, 'APPROVED'::text, 'REJECTED'::text, 'NEED_UPDATE'::text])))
);


--
-- Name: mentor_skills; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.mentor_skills (
    id integer NOT NULL,
    mentor_member_id integer NOT NULL,
    skill_id integer NOT NULL,
    display_order integer DEFAULT 0 NOT NULL
);


--
-- Name: mentor_skills_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.mentor_skills ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.mentor_skills_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: mentorship_reports; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.mentorship_reports (
    id integer NOT NULL,
    session_id integer,
    reporter_member_id integer,
    reported_member_id integer,
    reason_category text,
    description text,
    status text,
    created_at timestamp without time zone
);


--
-- Name: mentorship_reports_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.mentorship_reports ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.mentorship_reports_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: mentorship_sessions; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.mentorship_sessions (
    id integer NOT NULL,
    availability_id integer,
    mentee_member_id integer,
    status text,
    booking_note text,
    meeting_link text,
    session_type text,
    introduction text,
    description text,
    cv_url text,
    cancel_reason text,
    proposed_start_time timestamp without time zone,
    proposed_end_time timestamp without time zone,
    mentor_joined_at timestamp without time zone,
    mentee_joined_at timestamp without time zone,
    started_at timestamp without time zone,
    ended_at timestamp without time zone,
    meeting_link_reminded_at timestamp without time zone,
    created_at timestamp without time zone
);


--
-- Name: mentorship_sessions_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.mentorship_sessions ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.mentorship_sessions_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: news; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.news (
    id integer NOT NULL,
    organization_id integer,
    author_member_id integer,
    title text,
    slug text,
    content text,
    thumbnail_url text,
    topic text,
    url text,
    is_hidden boolean,
    published_at timestamp without time zone,
    created_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
    updated_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP
);


--
-- Name: news_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.news ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.news_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: notifications; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.notifications (
    id integer NOT NULL,
    member_id integer,
    title text,
    message text,
    is_read boolean,
    link text,
    created_at timestamp without time zone
);


--
-- Name: notifications_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.notifications ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.notifications_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: organization_introductions; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.organization_introductions (
    id integer NOT NULL,
    orga_id integer,
    content text,
    vision text,
    mission text,
    core_values text,
    image_urls text,
    banner_url text,
    leaders jsonb,
    team_members jsonb,
    leaders_content text,
    team_members_content text,
    updated_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP
);


--
-- Name: organization_introductions_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.organization_introductions ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.organization_introductions_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: organization_members; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.organization_members (
    id integer NOT NULL,
    organization_id integer,
    user_id integer,
    student_id text,
    started_year jsonb,
    graduated_year jsonb,
    graduation_status jsonb,
    program jsonb,
    major jsonb,
    faculty jsonb,
    department jsonb,
    verification_level integer DEFAULT 0,
    is_trusted_verifier boolean DEFAULT false,
    status text DEFAULT 'ACTIVE'::text,
    created_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
    updated_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP
);


--
-- Name: organization_members_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.organization_members ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.organization_members_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: organizations; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.organizations (
    id integer NOT NULL,
    name text,
    slug text,
    logo_url text,
    brand_config jsonb,
    features_config jsonb,
    programs jsonb,
    majors jsonb,
    status text DEFAULT 'ACTIVE'::text,
    created_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
    updated_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
    contact_phone text,
    contact_email text,
    department_name text
);


--
-- Name: organizations_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.organizations ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.organizations_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: peer_verifications; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.peer_verifications (
    id integer NOT NULL,
    target_member_id integer,
    verifier_member_id integer,
    status text DEFAULT 'PENDING'::text,
    created_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
    organization_id integer
);


--
-- Name: peer_verifications_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.peer_verifications ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.peer_verifications_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: review_rules; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.review_rules (
    id integer NOT NULL,
    domain text NOT NULL,
    decision text NOT NULL,
    condition_description text NOT NULL,
    is_active boolean DEFAULT true NOT NULL,
    priority integer DEFAULT 0 NOT NULL,
    created_by_member_id integer,
    created_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
    updated_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP
);


--
-- Name: review_rules_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

CREATE SEQUENCE public.review_rules_id_seq
    AS integer
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


--
-- Name: review_rules_id_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: -
--

ALTER SEQUENCE public.review_rules_id_seq OWNED BY public.review_rules.id;


--
-- Name: review_suggestions; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.review_suggestions (
    id integer NOT NULL,
    domain text NOT NULL,
    target_id integer NOT NULL,
    suggested_decision text NOT NULL,
    matched_rules text,
    ai_explanation text,
    confidence integer,
    created_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP
);


--
-- Name: review_suggestions_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

CREATE SEQUENCE public.review_suggestions_id_seq
    AS integer
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


--
-- Name: review_suggestions_id_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: -
--

ALTER SEQUENCE public.review_suggestions_id_seq OWNED BY public.review_suggestions.id;


--
-- Name: saved_items; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.saved_items (
    id integer NOT NULL,
    member_id integer,
    item_type text,
    item_id integer,
    note text,
    saved_at timestamp without time zone
);


--
-- Name: saved_items_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.saved_items ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.saved_items_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: school_feedbacks; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.school_feedbacks (
    id integer NOT NULL,
    organization_id integer NOT NULL,
    full_name text,
    phone text,
    email text,
    subject text,
    ai_summary text,
    content text NOT NULL,
    created_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
    is_read boolean DEFAULT false
);


--
-- Name: school_feedbacks_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.school_feedbacks ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.school_feedbacks_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: session_feedbacks; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.session_feedbacks (
    id integer NOT NULL,
    session_id integer,
    mentee_member_id integer,
    rating integer,
    comment text,
    is_public boolean,
    created_at timestamp without time zone
);


--
-- Name: session_feedbacks_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.session_feedbacks ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.session_feedbacks_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: skills; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.skills (
    id integer NOT NULL,
    name text NOT NULL,
    created_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP NOT NULL
);


--
-- Name: skills_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.skills ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.skills_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: survey_forms; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.survey_forms (
    id bigint NOT NULL,
    organization_id bigint NOT NULL,
    creator_member_id bigint,
    title character varying(255) NOT NULL,
    description text,
    questions_data jsonb DEFAULT '[]'::jsonb NOT NULL,
    start_at timestamp without time zone NOT NULL,
    duration_minutes integer NOT NULL,
    status character varying(30) DEFAULT 'DRAFT'::character varying NOT NULL,
    allow_multiple boolean DEFAULT false NOT NULL,
    created_at timestamp without time zone DEFAULT now() NOT NULL,
    updated_at timestamp without time zone DEFAULT now() NOT NULL
);


--
-- Name: survey_forms_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

CREATE SEQUENCE public.survey_forms_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


--
-- Name: survey_forms_id_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: -
--

ALTER SEQUENCE public.survey_forms_id_seq OWNED BY public.survey_forms.id;


--
-- Name: survey_submissions; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.survey_submissions (
    id bigint NOT NULL,
    form_id bigint NOT NULL,
    member_id bigint,
    answers_data jsonb NOT NULL,
    submitted_at timestamp without time zone DEFAULT now() NOT NULL
);


--
-- Name: survey_submissions_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

CREATE SEQUENCE public.survey_submissions_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


--
-- Name: survey_submissions_id_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: -
--

ALTER SEQUENCE public.survey_submissions_id_seq OWNED BY public.survey_submissions.id;


--
-- Name: user_blocks; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.user_blocks (
    id bigint NOT NULL,
    blocker_member_id integer NOT NULL,
    blocked_member_id integer NOT NULL,
    created_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP
);


--
-- Name: user_blocks_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

CREATE SEQUENCE public.user_blocks_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


--
-- Name: user_blocks_id_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: -
--

ALTER SEQUENCE public.user_blocks_id_seq OWNED BY public.user_blocks.id;


--
-- Name: user_login_histories; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.user_login_histories (
    id bigint NOT NULL,
    user_id integer NOT NULL,
    login_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
    login_method text,
    login_ip text,
    user_agent text
);


--
-- Name: user_login_histories_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

CREATE SEQUENCE public.user_login_histories_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


--
-- Name: user_login_histories_id_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: -
--

ALTER SEQUENCE public.user_login_histories_id_seq OWNED BY public.user_login_histories.id;


--
-- Name: user_notification_settings; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.user_notification_settings (
    user_id integer NOT NULL,
    email_enabled boolean DEFAULT true,
    push_enabled boolean DEFAULT true,
    event_reminder_enabled boolean DEFAULT true,
    news_enabled boolean DEFAULT true,
    forum_reply_enabled boolean DEFAULT true,
    updated_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP
);


--
-- Name: users; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.users (
    id integer NOT NULL,
    email text,
    password_hash text,
    status text,
    role text,
    avatar_url text,
    created_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
    updated_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
    full_name text,
    phone text,
    bio text,
    dob date,
    gender text,
    settings jsonb,
    must_change_password boolean DEFAULT false NOT NULL,
    current_job_title text,
    current_company text,
    links jsonb,
    cover_url character varying(255)
);


--
-- Name: users_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.users ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.users_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: verification_requests; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.verification_requests (
    id integer NOT NULL,
    member_id integer,
    document_url text,
    document_type text,
    ai_summary text,
    status text,
    admin_note text,
    reviewed_by_member_id integer,
    created_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
    updated_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
    organization_id integer
);


--
-- Name: verification_requests_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.verification_requests ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.verification_requests_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: admin_audit_logs id; Type: DEFAULT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.admin_audit_logs ALTER COLUMN id SET DEFAULT nextval('public.admin_audit_logs_id_seq'::regclass);


--
-- Name: chat_conversation_requests id; Type: DEFAULT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.chat_conversation_requests ALTER COLUMN id SET DEFAULT nextval('public.chat_conversation_requests_id_seq'::regclass);


--
-- Name: email_templates id; Type: DEFAULT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.email_templates ALTER COLUMN id SET DEFAULT nextval('public.email_templates_id_seq'::regclass);


--
-- Name: forum_post_reports id; Type: DEFAULT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.forum_post_reports ALTER COLUMN id SET DEFAULT nextval('public.forum_post_reports_id_seq'::regclass);


--
-- Name: fund_donations id; Type: DEFAULT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.fund_donations ALTER COLUMN id SET DEFAULT nextval('public.fund_donations_id_seq'::regclass);


--
-- Name: fund_receiving_infos id; Type: DEFAULT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.fund_receiving_infos ALTER COLUMN id SET DEFAULT nextval('public.fund_receiving_infos_id_seq'::regclass);


--
-- Name: funds id; Type: DEFAULT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.funds ALTER COLUMN id SET DEFAULT nextval('public.funds_id_seq'::regclass);


--
-- Name: review_rules id; Type: DEFAULT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.review_rules ALTER COLUMN id SET DEFAULT nextval('public.review_rules_id_seq'::regclass);


--
-- Name: review_suggestions id; Type: DEFAULT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.review_suggestions ALTER COLUMN id SET DEFAULT nextval('public.review_suggestions_id_seq'::regclass);


--
-- Name: survey_forms id; Type: DEFAULT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.survey_forms ALTER COLUMN id SET DEFAULT nextval('public.survey_forms_id_seq'::regclass);


--
-- Name: survey_submissions id; Type: DEFAULT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.survey_submissions ALTER COLUMN id SET DEFAULT nextval('public.survey_submissions_id_seq'::regclass);


--
-- Name: user_blocks id; Type: DEFAULT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.user_blocks ALTER COLUMN id SET DEFAULT nextval('public.user_blocks_id_seq'::regclass);


--
-- Name: user_login_histories id; Type: DEFAULT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.user_login_histories ALTER COLUMN id SET DEFAULT nextval('public.user_login_histories_id_seq'::regclass);


--
-- Name: achievements achievements_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.achievements
    ADD CONSTRAINT achievements_pkey PRIMARY KEY (id);


--
-- Name: admin_audit_logs admin_audit_logs_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.admin_audit_logs
    ADD CONSTRAINT admin_audit_logs_pkey PRIMARY KEY (id);


--
-- Name: ai_models ai_models_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.ai_models
    ADD CONSTRAINT ai_models_pkey PRIMARY KEY (id);


--
-- Name: ai_providers ai_providers_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.ai_providers
    ADD CONSTRAINT ai_providers_pkey PRIMARY KEY (id);


--
-- Name: alumni_posts alumni_posts_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.alumni_posts
    ADD CONSTRAINT alumni_posts_pkey PRIMARY KEY (id);


--
-- Name: chat_conversation_requests chat_conversation_requests_chat_group_id_key; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.chat_conversation_requests
    ADD CONSTRAINT chat_conversation_requests_chat_group_id_key UNIQUE (chat_group_id);


--
-- Name: chat_conversation_requests chat_conversation_requests_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.chat_conversation_requests
    ADD CONSTRAINT chat_conversation_requests_pkey PRIMARY KEY (id);


--
-- Name: chat_group_members chat_group_members_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.chat_group_members
    ADD CONSTRAINT chat_group_members_pkey PRIMARY KEY (id);


--
-- Name: chat_groups chat_groups_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.chat_groups
    ADD CONSTRAINT chat_groups_pkey PRIMARY KEY (id);


--
-- Name: chat_messages chat_messages_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.chat_messages
    ADD CONSTRAINT chat_messages_pkey PRIMARY KEY (id);


--
-- Name: device_tokens device_tokens_fcm_token_key; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.device_tokens
    ADD CONSTRAINT device_tokens_fcm_token_key UNIQUE (fcm_token);


--
-- Name: device_tokens device_tokens_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.device_tokens
    ADD CONSTRAINT device_tokens_pkey PRIMARY KEY (id);


--
-- Name: education_change_requests education_change_requests_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.education_change_requests
    ADD CONSTRAINT education_change_requests_pkey PRIMARY KEY (id);


--
-- Name: email_templates email_templates_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.email_templates
    ADD CONSTRAINT email_templates_pkey PRIMARY KEY (id);


--
-- Name: email_templates email_templates_template_code_key; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.email_templates
    ADD CONSTRAINT email_templates_template_code_key UNIQUE (template_code);


--
-- Name: event_email_logs event_email_logs_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.event_email_logs
    ADD CONSTRAINT event_email_logs_pkey PRIMARY KEY (id);


--
-- Name: event_interests event_interests_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.event_interests
    ADD CONSTRAINT event_interests_pkey PRIMARY KEY (id);


--
-- Name: event_invitations event_invitations_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.event_invitations
    ADD CONSTRAINT event_invitations_pkey PRIMARY KEY (id);


--
-- Name: event_invitations event_invitations_token_key; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.event_invitations
    ADD CONSTRAINT event_invitations_token_key UNIQUE (token);


--
-- Name: event_questions event_questions_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.event_questions
    ADD CONSTRAINT event_questions_pkey PRIMARY KEY (id);


--
-- Name: event_tickets event_tickets_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.event_tickets
    ADD CONSTRAINT event_tickets_pkey PRIMARY KEY (id);


--
-- Name: event_tickets event_tickets_ticket_code_key; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.event_tickets
    ADD CONSTRAINT event_tickets_ticket_code_key UNIQUE (ticket_code);


--
-- Name: events events_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.events
    ADD CONSTRAINT events_pkey PRIMARY KEY (id);


--
-- Name: forum_categories forum_categories_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.forum_categories
    ADD CONSTRAINT forum_categories_pkey PRIMARY KEY (id);


--
-- Name: forum_post_reactions forum_post_reactions_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.forum_post_reactions
    ADD CONSTRAINT forum_post_reactions_pkey PRIMARY KEY (id);


--
-- Name: forum_post_reports forum_post_reports_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.forum_post_reports
    ADD CONSTRAINT forum_post_reports_pkey PRIMARY KEY (id);


--
-- Name: forum_posts forum_posts_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.forum_posts
    ADD CONSTRAINT forum_posts_pkey PRIMARY KEY (id);


--
-- Name: forum_topic_subscriptions forum_topic_subscriptions_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.forum_topic_subscriptions
    ADD CONSTRAINT forum_topic_subscriptions_pkey PRIMARY KEY (id);


--
-- Name: forum_topics forum_topics_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.forum_topics
    ADD CONSTRAINT forum_topics_pkey PRIMARY KEY (id);


--
-- Name: fund_donations fund_donations_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.fund_donations
    ADD CONSTRAINT fund_donations_pkey PRIMARY KEY (id);


--
-- Name: fund_receiving_infos fund_receiving_infos_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.fund_receiving_infos
    ADD CONSTRAINT fund_receiving_infos_pkey PRIMARY KEY (id);


--
-- Name: funds funds_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.funds
    ADD CONSTRAINT funds_pkey PRIMARY KEY (id);


--
-- Name: jobs jobs_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.jobs
    ADD CONSTRAINT jobs_pkey PRIMARY KEY (id);


--
-- Name: learning_resources learning_resources_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.learning_resources
    ADD CONSTRAINT learning_resources_pkey PRIMARY KEY (id);


--
-- Name: mentee_profiles mentee_profiles_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.mentee_profiles
    ADD CONSTRAINT mentee_profiles_pkey PRIMARY KEY (member_id);


--
-- Name: mentor_availabilities mentor_availabilities_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.mentor_availabilities
    ADD CONSTRAINT mentor_availabilities_pkey PRIMARY KEY (id);


--
-- Name: mentor_expertise mentor_expertise_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.mentor_expertise
    ADD CONSTRAINT mentor_expertise_pkey PRIMARY KEY (id);


--
-- Name: mentor_profiles mentor_profiles_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.mentor_profiles
    ADD CONSTRAINT mentor_profiles_pkey PRIMARY KEY (member_id);


--
-- Name: mentor_skills mentor_skills_mentor_member_id_skill_id_key; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.mentor_skills
    ADD CONSTRAINT mentor_skills_mentor_member_id_skill_id_key UNIQUE (mentor_member_id, skill_id);


--
-- Name: mentor_skills mentor_skills_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.mentor_skills
    ADD CONSTRAINT mentor_skills_pkey PRIMARY KEY (id);


--
-- Name: mentorship_reports mentorship_reports_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.mentorship_reports
    ADD CONSTRAINT mentorship_reports_pkey PRIMARY KEY (id);


--
-- Name: mentorship_sessions mentorship_sessions_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.mentorship_sessions
    ADD CONSTRAINT mentorship_sessions_pkey PRIMARY KEY (id);


--
-- Name: news news_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.news
    ADD CONSTRAINT news_pkey PRIMARY KEY (id);


--
-- Name: notifications notifications_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.notifications
    ADD CONSTRAINT notifications_pkey PRIMARY KEY (id);


--
-- Name: organization_introductions organization_introductions_orga_id_key; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.organization_introductions
    ADD CONSTRAINT organization_introductions_orga_id_key UNIQUE (orga_id);


--
-- Name: organization_introductions organization_introductions_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.organization_introductions
    ADD CONSTRAINT organization_introductions_pkey PRIMARY KEY (id);


--
-- Name: organization_members organization_members_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.organization_members
    ADD CONSTRAINT organization_members_pkey PRIMARY KEY (id);


--
-- Name: organizations organizations_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.organizations
    ADD CONSTRAINT organizations_pkey PRIMARY KEY (id);


--
-- Name: organizations organizations_slug_key; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.organizations
    ADD CONSTRAINT organizations_slug_key UNIQUE (slug);


--
-- Name: peer_verifications peer_verifications_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.peer_verifications
    ADD CONSTRAINT peer_verifications_pkey PRIMARY KEY (id);


--
-- Name: review_rules review_rules_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.review_rules
    ADD CONSTRAINT review_rules_pkey PRIMARY KEY (id);


--
-- Name: review_suggestions review_suggestions_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.review_suggestions
    ADD CONSTRAINT review_suggestions_pkey PRIMARY KEY (id);


--
-- Name: saved_items saved_items_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.saved_items
    ADD CONSTRAINT saved_items_pkey PRIMARY KEY (id);


--
-- Name: school_feedbacks school_feedbacks_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.school_feedbacks
    ADD CONSTRAINT school_feedbacks_pkey PRIMARY KEY (id);


--
-- Name: session_feedbacks session_feedbacks_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.session_feedbacks
    ADD CONSTRAINT session_feedbacks_pkey PRIMARY KEY (id);


--
-- Name: skills skills_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.skills
    ADD CONSTRAINT skills_pkey PRIMARY KEY (id);


--
-- Name: survey_forms survey_forms_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.survey_forms
    ADD CONSTRAINT survey_forms_pkey PRIMARY KEY (id);


--
-- Name: survey_submissions survey_submissions_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.survey_submissions
    ADD CONSTRAINT survey_submissions_pkey PRIMARY KEY (id);


--
-- Name: fund_receiving_infos uk_fund_receiving_infos_bank_account; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.fund_receiving_infos
    ADD CONSTRAINT uk_fund_receiving_infos_bank_account UNIQUE (bank_name, account_number);


--
-- Name: organization_members uk_organization_members_org_user; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.organization_members
    ADD CONSTRAINT uk_organization_members_org_user UNIQUE (organization_id, user_id);


--
-- Name: organization_members uk_organization_members_student_id; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.organization_members
    ADD CONSTRAINT uk_organization_members_student_id UNIQUE (organization_id, student_id);


--
-- Name: user_blocks user_blocks_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.user_blocks
    ADD CONSTRAINT user_blocks_pkey PRIMARY KEY (id);


--
-- Name: user_login_histories user_login_histories_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.user_login_histories
    ADD CONSTRAINT user_login_histories_pkey PRIMARY KEY (id);


--
-- Name: user_notification_settings user_notification_settings_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.user_notification_settings
    ADD CONSTRAINT user_notification_settings_pkey PRIMARY KEY (user_id);


--
-- Name: users users_email_key; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.users
    ADD CONSTRAINT users_email_key UNIQUE (email);


--
-- Name: users users_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.users
    ADD CONSTRAINT users_pkey PRIMARY KEY (id);


--
-- Name: verification_requests verification_requests_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.verification_requests
    ADD CONSTRAINT verification_requests_pkey PRIMARY KEY (id);


--
-- Name: admin_audit_logs_target_user_id_created_at_idx; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX admin_audit_logs_target_user_id_created_at_idx ON public.admin_audit_logs USING btree (target_user_id, created_at DESC);


--
-- Name: chat_conversation_requests_member_low_id_member_high_id_idx; Type: INDEX; Schema: public; Owner: -
--

CREATE UNIQUE INDEX chat_conversation_requests_member_low_id_member_high_id_idx ON public.chat_conversation_requests USING btree (member_low_id, member_high_id);


--
-- Name: chat_group_members_group_id_member_id_idx; Type: INDEX; Schema: public; Owner: -
--

CREATE UNIQUE INDEX chat_group_members_group_id_member_id_idx ON public.chat_group_members USING btree (group_id, member_id);


--
-- Name: chat_group_members_member_id_idx; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX chat_group_members_member_id_idx ON public.chat_group_members USING btree (member_id);


--
-- Name: chat_messages_group_id_created_at_idx; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX chat_messages_group_id_created_at_idx ON public.chat_messages USING btree (group_id, created_at DESC);


--
-- Name: event_email_logs_event_id_sent_at_idx; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX event_email_logs_event_id_sent_at_idx ON public.event_email_logs USING btree (event_id, sent_at DESC);


--
-- Name: event_interests_event_id_member_id_idx; Type: INDEX; Schema: public; Owner: -
--

CREATE UNIQUE INDEX event_interests_event_id_member_id_idx ON public.event_interests USING btree (event_id, member_id);


--
-- Name: event_invitations_event_id_status_idx; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX event_invitations_event_id_status_idx ON public.event_invitations USING btree (event_id, status);


--
-- Name: event_invitations_token_idx; Type: INDEX; Schema: public; Owner: -
--

CREATE UNIQUE INDEX event_invitations_token_idx ON public.event_invitations USING btree (token);


--
-- Name: event_tickets_event_id_status_idx; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX event_tickets_event_id_status_idx ON public.event_tickets USING btree (event_id, status);


--
-- Name: event_tickets_member_id_idx; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX event_tickets_member_id_idx ON public.event_tickets USING btree (member_id);


--
-- Name: forum_post_reactions_post_id_member_id_idx; Type: INDEX; Schema: public; Owner: -
--

CREATE UNIQUE INDEX forum_post_reactions_post_id_member_id_idx ON public.forum_post_reactions USING btree (post_id, member_id);


--
-- Name: forum_post_reports_post_id_idx; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX forum_post_reports_post_id_idx ON public.forum_post_reports USING btree (post_id);


--
-- Name: forum_post_reports_status_created_at_idx; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX forum_post_reports_status_created_at_idx ON public.forum_post_reports USING btree (status, created_at DESC);


--
-- Name: forum_posts_topic_id_created_at_idx; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX forum_posts_topic_id_created_at_idx ON public.forum_posts USING btree (topic_id, created_at DESC);


--
-- Name: forum_topic_subscriptions_topic_id_member_id_idx; Type: INDEX; Schema: public; Owner: -
--

CREATE UNIQUE INDEX forum_topic_subscriptions_topic_id_member_id_idx ON public.forum_topic_subscriptions USING btree (topic_id, member_id);


--
-- Name: forum_topic_subscriptions_topic_id_member_id_last_read_at_l_idx; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX forum_topic_subscriptions_topic_id_member_id_last_read_at_l_idx ON public.forum_topic_subscriptions USING btree (topic_id, member_id, last_read_at, last_notified_at);


--
-- Name: idx_admin_audit_logs_action; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_admin_audit_logs_action ON public.admin_audit_logs USING btree (action);


--
-- Name: idx_admin_audit_logs_admin_user; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_admin_audit_logs_admin_user ON public.admin_audit_logs USING btree (admin_user_id, created_at DESC);


--
-- Name: idx_admin_audit_logs_created_at; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_admin_audit_logs_created_at ON public.admin_audit_logs USING btree (created_at DESC);


--
-- Name: idx_admin_audit_logs_resource_type; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_admin_audit_logs_resource_type ON public.admin_audit_logs USING btree (resource_type);


--
-- Name: idx_ai_models_provider; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_ai_models_provider ON public.ai_models USING btree (provider_id);


--
-- Name: idx_device_tokens_user; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_device_tokens_user ON public.device_tokens USING btree (user_id);


--
-- Name: idx_education_change_requests_member; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_education_change_requests_member ON public.education_change_requests USING btree (member_id);


--
-- Name: idx_education_change_requests_org_status; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_education_change_requests_org_status ON public.education_change_requests USING btree (organization_id, status);


--
-- Name: idx_event_questions_event; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_event_questions_event ON public.event_questions USING btree (event_id);


--
-- Name: idx_forum_posts_content_trgm; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_forum_posts_content_trgm ON public.forum_posts USING gin (content public.gin_trgm_ops);


--
-- Name: idx_forum_topics_title_trgm; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_forum_topics_title_trgm ON public.forum_topics USING gin (title public.gin_trgm_ops);


--
-- Name: idx_mentor_skills_mentor; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_mentor_skills_mentor ON public.mentor_skills USING btree (mentor_member_id);


--
-- Name: idx_mentor_skills_skill; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_mentor_skills_skill ON public.mentor_skills USING btree (skill_id);


--
-- Name: idx_notifications_member; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_notifications_member ON public.notifications USING btree (member_id);


--
-- Name: idx_organization_members_major_gin; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_organization_members_major_gin ON public.organization_members USING gin (major);


--
-- Name: idx_organization_members_program_gin; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_organization_members_program_gin ON public.organization_members USING gin (program);


--
-- Name: idx_peer_verifications_org; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_peer_verifications_org ON public.peer_verifications USING btree (organization_id);


--
-- Name: idx_review_rules_domain; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_review_rules_domain ON public.review_rules USING btree (domain);


--
-- Name: idx_review_suggestions_domain_target; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_review_suggestions_domain_target ON public.review_suggestions USING btree (domain, target_id);


--
-- Name: idx_sessions_status; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_sessions_status ON public.mentorship_sessions USING btree (status);


--
-- Name: idx_skills_name_lower; Type: INDEX; Schema: public; Owner: -
--

CREATE UNIQUE INDEX idx_skills_name_lower ON public.skills USING btree (lower(name));


--
-- Name: idx_survey_forms_org; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_survey_forms_org ON public.survey_forms USING btree (organization_id);


--
-- Name: idx_survey_forms_status; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_survey_forms_status ON public.survey_forms USING btree (status);


--
-- Name: idx_survey_submissions_form; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_survey_submissions_form ON public.survey_submissions USING btree (form_id);


--
-- Name: idx_survey_submissions_member; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_survey_submissions_member ON public.survey_submissions USING btree (form_id, member_id);


--
-- Name: idx_users_email_trgm; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_users_email_trgm ON public.users USING gin (email public.gin_trgm_ops);


--
-- Name: idx_users_name_trgm; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_users_name_trgm ON public.users USING gin (full_name public.gin_trgm_ops);


--
-- Name: idx_users_role; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_users_role ON public.users USING btree (role);


--
-- Name: idx_users_status; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_users_status ON public.users USING btree (status);


--
-- Name: idx_verification_requests_org; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_verification_requests_org ON public.verification_requests USING btree (organization_id);


--
-- Name: idx_verification_status; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_verification_status ON public.verification_requests USING btree (status);


--
-- Name: saved_items_member_id_item_type_item_id_idx; Type: INDEX; Schema: public; Owner: -
--

CREATE UNIQUE INDEX saved_items_member_id_item_type_item_id_idx ON public.saved_items USING btree (member_id, item_type, item_id);


--
-- Name: school_feedbacks_organization_id_is_read_created_at_idx; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX school_feedbacks_organization_id_is_read_created_at_idx ON public.school_feedbacks USING btree (organization_id, is_read, created_at DESC);


--
-- Name: uk_peer_verifications_org_target_verifier; Type: INDEX; Schema: public; Owner: -
--

CREATE UNIQUE INDEX uk_peer_verifications_org_target_verifier ON public.peer_verifications USING btree (organization_id, target_member_id, verifier_member_id);


--
-- Name: user_blocks_blocker_member_id_blocked_member_id_idx; Type: INDEX; Schema: public; Owner: -
--

CREATE UNIQUE INDEX user_blocks_blocker_member_id_blocked_member_id_idx ON public.user_blocks USING btree (blocker_member_id, blocked_member_id);


--
-- Name: user_login_histories_user_id_login_at_idx; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX user_login_histories_user_id_login_at_idx ON public.user_login_histories USING btree (user_id, login_at DESC);


--
-- Name: admin_audit_logs admin_audit_logs_admin_user_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.admin_audit_logs
    ADD CONSTRAINT admin_audit_logs_admin_user_id_fkey FOREIGN KEY (admin_user_id) REFERENCES public.users(id);


--
-- Name: admin_audit_logs admin_audit_logs_target_user_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.admin_audit_logs
    ADD CONSTRAINT admin_audit_logs_target_user_id_fkey FOREIGN KEY (target_user_id) REFERENCES public.users(id);


--
-- Name: ai_models ai_models_provider_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.ai_models
    ADD CONSTRAINT ai_models_provider_id_fkey FOREIGN KEY (provider_id) REFERENCES public.ai_providers(id) ON DELETE CASCADE;


--
-- Name: device_tokens device_tokens_user_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.device_tokens
    ADD CONSTRAINT device_tokens_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.users(id) ON DELETE CASCADE;


--
-- Name: education_change_requests education_change_requests_member_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.education_change_requests
    ADD CONSTRAINT education_change_requests_member_id_fkey FOREIGN KEY (member_id) REFERENCES public.organization_members(id) ON DELETE CASCADE;


--
-- Name: event_email_logs event_email_logs_event_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.event_email_logs
    ADD CONSTRAINT event_email_logs_event_id_fkey FOREIGN KEY (event_id) REFERENCES public.events(id);


--
-- Name: event_interests event_interests_event_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.event_interests
    ADD CONSTRAINT event_interests_event_id_fkey FOREIGN KEY (event_id) REFERENCES public.events(id);


--
-- Name: event_invitations event_invitations_event_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.event_invitations
    ADD CONSTRAINT event_invitations_event_id_fkey FOREIGN KEY (event_id) REFERENCES public.events(id);


--
-- Name: event_tickets event_tickets_event_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.event_tickets
    ADD CONSTRAINT event_tickets_event_id_fkey FOREIGN KEY (event_id) REFERENCES public.events(id);


--
-- Name: events events_organization_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.events
    ADD CONSTRAINT events_organization_id_fkey FOREIGN KEY (organization_id) REFERENCES public.organizations(id);


--
-- Name: mentor_skills fk_mentor_skills_mentor; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.mentor_skills
    ADD CONSTRAINT fk_mentor_skills_mentor FOREIGN KEY (mentor_member_id) REFERENCES public.mentor_profiles(member_id) ON DELETE CASCADE;


--
-- Name: mentor_skills fk_mentor_skills_skill; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.mentor_skills
    ADD CONSTRAINT fk_mentor_skills_skill FOREIGN KEY (skill_id) REFERENCES public.skills(id) ON DELETE CASCADE;


--
-- Name: peer_verifications fk_peer_verifications_organization; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.peer_verifications
    ADD CONSTRAINT fk_peer_verifications_organization FOREIGN KEY (organization_id) REFERENCES public.organizations(id);


--
-- Name: verification_requests fk_verification_requests_organization; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.verification_requests
    ADD CONSTRAINT fk_verification_requests_organization FOREIGN KEY (organization_id) REFERENCES public.organizations(id);


--
-- Name: forum_categories forum_categories_organization_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.forum_categories
    ADD CONSTRAINT forum_categories_organization_id_fkey FOREIGN KEY (organization_id) REFERENCES public.organizations(id);


--
-- Name: forum_post_reactions forum_post_reactions_post_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.forum_post_reactions
    ADD CONSTRAINT forum_post_reactions_post_id_fkey FOREIGN KEY (post_id) REFERENCES public.forum_posts(id);


--
-- Name: forum_post_reports forum_post_reports_post_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.forum_post_reports
    ADD CONSTRAINT forum_post_reports_post_id_fkey FOREIGN KEY (post_id) REFERENCES public.forum_posts(id);


--
-- Name: forum_post_reports forum_post_reports_reviewed_by_user_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.forum_post_reports
    ADD CONSTRAINT forum_post_reports_reviewed_by_user_id_fkey FOREIGN KEY (reviewed_by_user_id) REFERENCES public.users(id);


--
-- Name: forum_posts forum_posts_answer_to_post_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.forum_posts
    ADD CONSTRAINT forum_posts_answer_to_post_id_fkey FOREIGN KEY (answer_to_post_id) REFERENCES public.forum_posts(id);


--
-- Name: forum_posts forum_posts_topic_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.forum_posts
    ADD CONSTRAINT forum_posts_topic_id_fkey FOREIGN KEY (topic_id) REFERENCES public.forum_topics(id);


--
-- Name: forum_topic_subscriptions forum_topic_subscriptions_topic_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.forum_topic_subscriptions
    ADD CONSTRAINT forum_topic_subscriptions_topic_id_fkey FOREIGN KEY (topic_id) REFERENCES public.forum_topics(id);


--
-- Name: forum_topics forum_topics_category_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.forum_topics
    ADD CONSTRAINT forum_topics_category_id_fkey FOREIGN KEY (category_id) REFERENCES public.forum_categories(id);


--
-- Name: forum_topics forum_topics_organization_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.forum_topics
    ADD CONSTRAINT forum_topics_organization_id_fkey FOREIGN KEY (organization_id) REFERENCES public.organizations(id);


--
-- Name: fund_donations fund_donations_fund_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.fund_donations
    ADD CONSTRAINT fund_donations_fund_id_fkey FOREIGN KEY (fund_id) REFERENCES public.funds(id);


--
-- Name: funds funds_organization_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.funds
    ADD CONSTRAINT funds_organization_id_fkey FOREIGN KEY (organization_id) REFERENCES public.organizations(id);


--
-- Name: jobs jobs_organization_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.jobs
    ADD CONSTRAINT jobs_organization_id_fkey FOREIGN KEY (organization_id) REFERENCES public.organizations(id);


--
-- Name: learning_resources learning_resources_organization_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.learning_resources
    ADD CONSTRAINT learning_resources_organization_id_fkey FOREIGN KEY (organization_id) REFERENCES public.organizations(id);


--
-- Name: mentor_availabilities mentor_availabilities_mentor_member_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.mentor_availabilities
    ADD CONSTRAINT mentor_availabilities_mentor_member_id_fkey FOREIGN KEY (mentor_member_id) REFERENCES public.mentor_profiles(member_id);


--
-- Name: mentor_expertise mentor_expertise_mentor_member_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.mentor_expertise
    ADD CONSTRAINT mentor_expertise_mentor_member_id_fkey FOREIGN KEY (mentor_member_id) REFERENCES public.mentor_profiles(member_id);


--
-- Name: mentorship_reports mentorship_reports_session_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.mentorship_reports
    ADD CONSTRAINT mentorship_reports_session_id_fkey FOREIGN KEY (session_id) REFERENCES public.mentorship_sessions(id);


--
-- Name: mentorship_sessions mentorship_sessions_availability_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.mentorship_sessions
    ADD CONSTRAINT mentorship_sessions_availability_id_fkey FOREIGN KEY (availability_id) REFERENCES public.mentor_availabilities(id);


--
-- Name: news news_organization_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.news
    ADD CONSTRAINT news_organization_id_fkey FOREIGN KEY (organization_id) REFERENCES public.organizations(id);


--
-- Name: organization_introductions organization_introductions_orga_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.organization_introductions
    ADD CONSTRAINT organization_introductions_orga_id_fkey FOREIGN KEY (orga_id) REFERENCES public.organizations(id) ON DELETE CASCADE;


--
-- Name: organization_members organization_members_organization_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.organization_members
    ADD CONSTRAINT organization_members_organization_id_fkey FOREIGN KEY (organization_id) REFERENCES public.organizations(id);


--
-- Name: organization_members organization_members_user_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.organization_members
    ADD CONSTRAINT organization_members_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.users(id);


--
-- Name: school_feedbacks school_feedbacks_organization_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.school_feedbacks
    ADD CONSTRAINT school_feedbacks_organization_id_fkey FOREIGN KEY (organization_id) REFERENCES public.organizations(id);


--
-- Name: session_feedbacks session_feedbacks_session_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.session_feedbacks
    ADD CONSTRAINT session_feedbacks_session_id_fkey FOREIGN KEY (session_id) REFERENCES public.mentorship_sessions(id);


--
-- Name: survey_submissions survey_submissions_form_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.survey_submissions
    ADD CONSTRAINT survey_submissions_form_id_fkey FOREIGN KEY (form_id) REFERENCES public.survey_forms(id) ON DELETE CASCADE;


--
-- Name: user_login_histories user_login_histories_user_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.user_login_histories
    ADD CONSTRAINT user_login_histories_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.users(id);


--
-- Name: user_notification_settings user_notification_settings_user_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.user_notification_settings
    ADD CONSTRAINT user_notification_settings_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.users(id);


--
-- PostgreSQL database dump complete
--


