CREATE TABLE IF NOT EXISTS public.fitbot_knowledge_documents (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    source_name text NOT NULL UNIQUE,
    title text NOT NULL,
    content text NOT NULL,
    enabled boolean NOT NULL DEFAULT true,
    sync_status text NOT NULL DEFAULT 'PENDING',
    sync_error text,
    last_synced_at timestamp without time zone,
    created_at timestamp without time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at timestamp without time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_by bigint,
    CONSTRAINT fitbot_knowledge_title_not_blank_chk CHECK (length(trim(title)) > 0),
    CONSTRAINT fitbot_knowledge_content_not_blank_chk CHECK (length(trim(content)) > 0),
    CONSTRAINT fitbot_knowledge_sync_status_chk CHECK (sync_status IN ('PENDING', 'SYNCED', 'FAILED'))
);

CREATE INDEX IF NOT EXISTS idx_fitbot_knowledge_enabled_updated
    ON public.fitbot_knowledge_documents (enabled, updated_at DESC);

CREATE INDEX IF NOT EXISTS idx_fitbot_knowledge_sync_status_updated
    ON public.fitbot_knowledge_documents (sync_status, updated_at DESC);
