CREATE TABLE IF NOT EXISTS event_comments (
    id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    event_id integer NOT NULL REFERENCES events(id),
    author_member_id integer NOT NULL,
    content text NOT NULL,
    parent_comment_id integer REFERENCES event_comments(id),
    is_hidden boolean DEFAULT false,
    created_at timestamp DEFAULT CURRENT_TIMESTAMP,
    updated_at timestamp DEFAULT CURRENT_TIMESTAMP
);
CREATE INDEX IF NOT EXISTS idx_event_comments_event_id ON event_comments (event_id, created_at);

CREATE TABLE IF NOT EXISTS news_comments (
    id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    news_id integer NOT NULL REFERENCES news(id),
    author_member_id integer NOT NULL,
    content text NOT NULL,
    parent_comment_id integer REFERENCES news_comments(id),
    is_hidden boolean DEFAULT false,
    created_at timestamp DEFAULT CURRENT_TIMESTAMP,
    updated_at timestamp DEFAULT CURRENT_TIMESTAMP
);
CREATE INDEX IF NOT EXISTS idx_news_comments_news_id ON news_comments (news_id, created_at);

CREATE TABLE IF NOT EXISTS alumni_post_comments (
    id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    alumni_post_id integer NOT NULL REFERENCES alumni_posts(id),
    author_member_id integer NOT NULL,
    content text NOT NULL,
    parent_comment_id integer REFERENCES alumni_post_comments(id),
    is_hidden boolean DEFAULT false,
    created_at timestamp DEFAULT CURRENT_TIMESTAMP,
    updated_at timestamp DEFAULT CURRENT_TIMESTAMP
);
CREATE INDEX IF NOT EXISTS idx_alumni_post_comments_post_id ON alumni_post_comments (alumni_post_id, created_at);
