-- Bảng lưu FCM device token để gửi push notification cho mobile.
-- Mỗi user có thể có nhiều token (nhiều thiết bị). Token là duy nhất toàn hệ thống;
-- khi 1 thiết bị đăng nhập tài khoản khác, token cũ được gán lại cho user mới.
-- Matches docs/postgre.sql. Idempotent — an toàn khi chạy nhiều lần trên local và cloud.

CREATE TABLE IF NOT EXISTS device_tokens
(
    id         integer generated by default as identity
        PRIMARY KEY,
    user_id    integer NOT NULL
        REFERENCES users (id) ON DELETE CASCADE,
    fcm_token  text    NOT NULL
        UNIQUE,
    platform   text,
    created_at timestamp DEFAULT CURRENT_TIMESTAMP,
    updated_at timestamp DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX IF NOT EXISTS idx_device_tokens_user
    ON device_tokens (user_id);
