CREATE TABLE IF NOT EXISTS ai_providers
(
    id            integer generated by default as identity
        PRIMARY KEY,
    name          text    NOT NULL,
    provider_type text    NOT NULL DEFAULT 'openai_compatible',
    base_url      text,
    api_key_enc   text,
    enabled       boolean NOT NULL DEFAULT true,
    priority      integer NOT NULL DEFAULT 0,
    created_at    timestamp DEFAULT CURRENT_TIMESTAMP,
    updated_at    timestamp DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS ai_models
(
    id          integer generated by default as identity
        PRIMARY KEY,
    provider_id integer NOT NULL
        REFERENCES ai_providers (id) ON DELETE CASCADE,
    model_name  text    NOT NULL,
    priority    integer NOT NULL DEFAULT 0,
    enabled     boolean NOT NULL DEFAULT true,
    created_at  timestamp DEFAULT CURRENT_TIMESTAMP,
    updated_at  timestamp DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX IF NOT EXISTS idx_ai_models_provider
    ON ai_models (provider_id);
