-- Event flow enhancements: questions, registration answers, cancel reason
-- Idempotent — safe to run on local and cloud. Matches docs/postgre.sql.

CREATE TABLE IF NOT EXISTS event_questions (
  id            INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  event_id      integer NOT NULL,
  type          text NOT NULL,
  label         text NOT NULL,
  options       text,
  required      boolean NOT NULL DEFAULT false,
  order_index   integer NOT NULL DEFAULT 0,
  created_at    timestamp DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX IF NOT EXISTS idx_event_questions_event ON event_questions(event_id);

ALTER TABLE event_tickets ADD COLUMN IF NOT EXISTS registration_answers text;
ALTER TABLE event_tickets ADD COLUMN IF NOT EXISTS cancel_reason text;

-- Normalize json/jsonb → text (R2DBC maps these columns as String; json caused 500s)
DO $$
BEGIN
  IF EXISTS (
    SELECT 1 FROM information_schema.columns
    WHERE table_schema = 'public' AND table_name = 'event_questions'
      AND column_name = 'options' AND data_type IN ('json', 'jsonb')
  ) THEN
    ALTER TABLE event_questions
      ALTER COLUMN options TYPE text USING options::text;
  END IF;

  IF EXISTS (
    SELECT 1 FROM information_schema.columns
    WHERE table_schema = 'public' AND table_name = 'event_tickets'
      AND column_name = 'registration_answers' AND data_type IN ('json', 'jsonb')
  ) THEN
    ALTER TABLE event_tickets
      ALTER COLUMN registration_answers TYPE text USING registration_answers::text;
  END IF;
END $$;
