-- Event flow enhancements: questions, registration answers, cancel reason

CREATE TABLE IF NOT EXISTS event_questions (
  id            INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  event_id      integer NOT NULL,
  type          text NOT NULL,
  label         text NOT NULL,
  options       text,
  required      boolean NOT NULL DEFAULT false,
  order_index   integer NOT NULL DEFAULT 0,
  created_at    timestamp DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX IF NOT EXISTS idx_event_questions_event ON event_questions(event_id);

ALTER TABLE event_tickets ADD COLUMN IF NOT EXISTS registration_answers text;
ALTER TABLE event_tickets ADD COLUMN IF NOT EXISTS cancel_reason text;
