-- Home/contact/profile configuration migration.
-- Run once on the cloud PostgreSQL database before deploying the matching backend.

ALTER TABLE users ADD COLUMN IF NOT EXISTS cover_url text;

UPDATE users u
SET cover_url = mp.cover_url
FROM mentor_profiles mp
WHERE mp.member_id = u.id
  AND u.cover_url IS NULL
  AND mp.cover_url IS NOT NULL;

UPDATE users u
SET bio = mp.bio
FROM mentor_profiles mp
WHERE mp.member_id = u.id
  AND (u.bio IS NULL OR btrim(u.bio) = '')
  AND mp.bio IS NOT NULL
  AND btrim(mp.bio) <> '';

CREATE TABLE IF NOT EXISTS organization_site_settings (
  organization_id integer PRIMARY KEY REFERENCES organizations(id) ON DELETE CASCADE,
  contact_office text,
  contact_address text,
  contact_email text,
  contact_phone text,
  contact_admissions_phone text,
  social_links json DEFAULT '{}'::json,
  updated_at timestamp DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS organization_featured_alumni (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  organization_id integer NOT NULL REFERENCES organizations(id) ON DELETE CASCADE,
  user_id integer NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  display_order integer NOT NULL DEFAULT 0,
  note text,
  created_at timestamp DEFAULT CURRENT_TIMESTAMP,
  updated_at timestamp DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT uq_organization_featured_alumni UNIQUE (organization_id, user_id),
  CONSTRAINT ck_organization_featured_alumni_order CHECK (display_order >= 0 AND display_order < 8)
);

CREATE INDEX IF NOT EXISTS idx_organization_featured_alumni_org_order
  ON organization_featured_alumni (organization_id, display_order, id);

-- image_urls already stores the home hero/introduction images. Keep only the first
-- five entries when existing rows contain JSON arrays longer than the UI limit.
UPDATE organization_introductions
SET image_urls = (
  SELECT COALESCE(json_agg(value), '[]'::json)
  FROM (
    SELECT value
    FROM json_array_elements(image_urls::json) WITH ORDINALITY AS items(value, ord)
    WHERE ord <= 5
    ORDER BY ord
  ) limited
)::text
WHERE image_urls IS NOT NULL
  AND image_urls ~ '^[[:space:]]*\['
  AND json_typeof(image_urls::json) = 'array'
  AND json_array_length(image_urls::json) > 5;

ALTER TABLE mentor_profiles DROP COLUMN IF EXISTS cover_url;
ALTER TABLE mentor_profiles DROP COLUMN IF EXISTS bio;
