-- 2026-07-06: Chuẩn hoá skill tag của mentor vào catalog dùng chung
--
-- Mục tiêu:
--   Thay vì lưu skill tag như chuỗi tự do trong mentor_expertise.category/topic
--   hoặc trong extended_profile (JSON), tạo bảng catalog "skills" (tên duy nhất)
--   và bảng nối "mentor_skills" lưu thứ tự ưu tiên (display_order) mà mentor tự
--   sắp xếp ở bước đăng ký. Nhờ đó trang filter "theo kỹ năng" có thể query
--   catalog trực tiếp (LIKE search, sort A-Z) thay vì SELECT DISTINCT trên dữ
--   liệu mô tả tự do.
--
--   Đồng thời migrate dữ liệu cũ: mỗi category/topic distinct hiện có trong
--   mentor_expertise được tạo thành 1 skill, và gán vào mentor_skills cho các
--   mentor tương ứng để không bị mất khỏi kết quả filter theo kỹ năng mới.

BEGIN;

CREATE TABLE IF NOT EXISTS "skills" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "name" text NOT NULL,
  "created_at" timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE UNIQUE INDEX IF NOT EXISTS "idx_skills_name_lower" ON "skills" (LOWER("name"));

CREATE TABLE IF NOT EXISTS "mentor_skills" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "mentor_member_id" integer NOT NULL,
  "skill_id" integer NOT NULL,
  "display_order" integer NOT NULL DEFAULT 0,
  UNIQUE ("mentor_member_id", "skill_id")
);

ALTER TABLE "mentor_skills" ADD CONSTRAINT "fk_mentor_skills_mentor"
  FOREIGN KEY ("mentor_member_id") REFERENCES "mentor_profiles" ("member_id") ON DELETE CASCADE;

ALTER TABLE "mentor_skills" ADD CONSTRAINT "fk_mentor_skills_skill"
  FOREIGN KEY ("skill_id") REFERENCES "skills" ("id") ON DELETE CASCADE;

CREATE INDEX IF NOT EXISTS "idx_mentor_skills_mentor" ON "mentor_skills" ("mentor_member_id");
CREATE INDEX IF NOT EXISTS "idx_mentor_skills_skill" ON "mentor_skills" ("skill_id");

-- Backfill: mỗi category/topic distinct (không rỗng) trong mentor_expertise -> 1 skill.
INSERT INTO "skills" ("name")
SELECT DISTINCT trim(v.value)
FROM mentor_expertise me
CROSS JOIN LATERAL (VALUES (me.category), (me.topic)) AS v(value)
WHERE v.value IS NOT NULL AND trim(v.value) <> ''
ON CONFLICT DO NOTHING;

-- Backfill: gán skill cho mentor tương ứng, thứ tự theo id của mentor_expertise (thứ tự nhập cũ).
INSERT INTO "mentor_skills" ("mentor_member_id", "skill_id", "display_order")
SELECT DISTINCT ON (me.mentor_member_id, s.id)
       me.mentor_member_id, s.id,
       row_number() OVER (PARTITION BY me.mentor_member_id ORDER BY me.id) - 1
FROM mentor_expertise me
CROSS JOIN LATERAL (VALUES (me.category), (me.topic)) AS v(value)
JOIN skills s ON LOWER(s.name) = LOWER(trim(v.value))
WHERE v.value IS NOT NULL AND trim(v.value) <> ''
  AND me.mentor_member_id IS NOT NULL
ON CONFLICT ("mentor_member_id", "skill_id") DO NOTHING;

COMMIT;
