export const DEFAULT_FORUM_TOPICS = [
  {
    id: 1,
    title: 'Career Networking',
    categoryId: 2,
    categoryName: 'Alumni Career',
    createdByMemberId: 5,
    createdByName: 'John Doe',
    postCount: 25,
    viewCount: 340,
    isActive: true,
    createdAt: '2026-03-01T10:00:00.000Z',
  },
  {
    id: 2,
    title: 'Alumni Startup Showcase',
    categoryId: 7,
    categoryName: 'Alumni Career',
    createdByMemberId: 8,
    createdByName: 'Mary Dao',
    postCount: 12,
    viewCount: 188,
    isActive: true,
    createdAt: '2026-04-01T09:12:00.000Z',
  },
  {
    id: 3,
    title: 'Campus Reunion 2025',
    categoryId: 3,
    categoryName: 'Events',
    createdByMemberId: 2,
    createdByName: 'Club Board',
    postCount: 42,
    viewCount: 1205,
    isActive: false,
    createdAt: '2025-11-20T14:00:00.000Z',
  },
];
