server.port=8080
spring.application.name=Alumniverse Backend
spring.profiles.active=dev

logging.level.root=INFO
logging.level.com.service.backend=INFO
logging.level.org.springframework.security=INFO
logging.level.org.springframework.web=INFO
logging.file.name=logs/application.log
logging.file.max-size=10MB
logging.file.max-history=30
logging.pattern.console=%d{yyyy-MM-dd HH:mm:ss} - %msg%n

spring.r2dbc.url=r2dbc:postgresql://localhost:5432/db?sslMode=disable
spring.r2dbc.username=user
spring.r2dbc.password=123
spring.r2dbc.pool.initial-size=10
spring.r2dbc.pool.max-size=20
spring.r2dbc.pool.max-idle-time=30m
spring.r2dbc.pool.max-acquire-time=3s
spring.r2dbc.pool.max-create-connection-time=2s

jwt.secret=your_secret_key_change_this_in_production_environment_with_minimum_256_bits
jwt.expiration_access=86400000
jwt.expiration_refresh=604800000

springdoc.api-docs.path=/v3/api-docs
springdoc.swagger-ui.path=/swagger-ui.html
springdoc.swagger-ui.enabled=true
springdoc.api-docs.enabled=true
springdoc.swagger-ui.operations-sorter=method
springdoc.swagger-ui.tags-sorter=alpha
springdoc.swagger-ui.doc-expansion=list

spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=nn5724735@gmail.com
spring.mail.password=bvvqflluvxwzxckc
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.properties.mail.smtp.starttls.required=true
spring.mail.properties.mail.smtp.connectiontimeout=5000
spring.mail.properties.mail.smtp.timeout=5000
spring.mail.properties.mail.smtp.writetimeout=5000

app.mail.from-address=nn5724735@gmail.com
app.mail.from-name=Alumniverse

# Caching Configuration for Bucket4j with Caffeine
spring.cache.type=caffeine
spring.cache.caffeine.spec=expireAfterWrite=15m

# Spring Security default user configuration
spring.security.user.name=admin
spring.security.user.password=admin@123456
payos.client-id=${PAYOS_CLIENT_ID}
payos.api-key=${PAYOS_API_KEY}
payos.checksum-key=${PAYOS_CHECKSUM_KEY}
payos.log-level=info
# forward den page return kem voi cac query param duoc payos gan vao
payos.return-url=http://localhost:8080/api/payment/return
# forward den page cancel kem voi cac query param duoc payos gan vao
payos.cancel-url=http://localhost:8080/api/payment/cancel