CREATE TABLE "users" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "email" text UNIQUE,
  "password_hash" text,
  "user_name" text UNIQUE,
  "status" text,
  "role" text,
  "avatar_url" text,
  "created_at" timestamp DEFAULT CURRENT_TIMESTAMP,
  "updated_at" timestamp DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE "global_profiles" (
  "user_id" integer PRIMARY KEY,
  "full_name" text,
  "phone" text,
  "bio" text,
  "dob" date,
  "gender" text,
  "settings" json,
  "updated_at" timestamp DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE "organizations" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "name" text,
  "slug" text UNIQUE,
  "logo_url" text,
  "brand_config" json,
  "features_config" json,
  "programs" json,
  "majors" json,
  "status" text DEFAULT 'ACTIVE',
  "created_at" timestamp DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE "organization_introductions" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "orga_id" integer UNIQUE REFERENCES organizations(id) ON DELETE CASCADE,
  "content" text,
  "vision" text,
  "mission" text,
  "core_values" text,
  "image_urls" text,
  "banner_url" text,
  "leaders" json,
  "team_members" json,
  "leaders_content" text, 
  "team_members_content" text,
  "updated_at" timestamp DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE "organization_members" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "organization_id" integer,
  "user_id" integer UNIQUE,
  "started_year" jsonb,
  "graduated_year" jsonb,
  "graduation_status" jsonb,
  "program" jsonb,
  "major" jsonb,
  "faculty" jsonb,
  "department" jsonb,
  "verification_level" integer DEFAULT 0,  -- 0: unverified, 1: requested, 2: accepted
  "is_trusted_verifier" boolean DEFAULT false,
  "status" text DEFAULT 'ACTIVE',
  "created_at" timestamp DEFAULT CURRENT_TIMESTAMP,
  "updated_at" timestamp DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX IF NOT EXISTS idx_organization_members_program_gin
  ON "organization_members" USING GIN ("program");

CREATE INDEX IF NOT EXISTS idx_organization_members_major_gin
  ON "organization_members" USING GIN ("major");


CREATE TABLE "peer_verifications" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "target_member_id" integer,
  "verifier_member_id" integer,
  "status" text DEFAULT 'PENDING',
  "created_at" timestamp DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE "verification_requests" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "member_id" integer,
  "document_url" text,
  "document_type" text,
  "ai_summary" text,
  "status" text,
  "admin_note" text,
  "reviewed_by_member_id" integer,
  "created_at" timestamp DEFAULT CURRENT_TIMESTAMP,
  "updated_at" timestamp DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE "events" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "organization_id" integer,
  "creator_member_id" integer,
  "title" text,
  "description" text,
  "banner_url" text,
  "location" text,
  "start_time" timestamp,
  "end_time" timestamp,
  "registration_start_at" timestamp,
  "registration_end_at" timestamp,
  "max_capacity" integer,
  "interested_count" integer DEFAULT 0,
  "topic" text,
  "is_published" boolean DEFAULT false,
  "created_at" timestamp
);

CREATE TABLE "event_interests" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "event_id" integer,
  "member_id" integer,
  "created_at" timestamp
);

CREATE TABLE "event_tickets" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "event_id" integer,
  "member_id" integer,
  "guest_name" text,
  "guest_email" text,
  "guest_phone" text,
  "ticket_code" text UNIQUE,
  "status" text NOT NULL DEFAULT 'PENDING',
  "registered_at" timestamp DEFAULT CURRENT_TIMESTAMP,
  "checked_in_at" timestamp,
  "reviewed_by" integer,        
  "reviewed_at" timestamp,
  "reject_reason" text
);

CREATE TABLE "event_invitations" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "event_id" integer NOT NULL,
  "member_id" integer,
  "email" text NOT NULL,
  "token" text UNIQUE NOT NULL,
  "status" text NOT NULL DEFAULT 'PENDING',
  "invited_by" integer NOT NULL,
  "invited_at" timestamp DEFAULT CURRENT_TIMESTAMP,
  "confirmed_at" timestamp,
  "expires_at" timestamp
);

CREATE TABLE "event_email_logs" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "event_id" integer NOT NULL,
  "sent_by" integer NOT NULL,
  "template_name" text,
  "subject" text,
  "recipient_count" integer DEFAULT 0,
  "sent_at" timestamp DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE "mentor_profiles" (
  "member_id" integer PRIMARY KEY,
  "current_job_title" text,
  "current_company" text,
  "bio" text,
  "rating_avg" decimal DEFAULT 0,
  "total_sessions" integer DEFAULT 0,
  "status" text NOT NULL DEFAULT 'DRAFT' CHECK ("status" IN ('DRAFT','PENDING','APPROVED','REJECTED','NEED_UPDATE')),
  "review_note" text,
  "reviewed_at" timestamp,
  "reviewed_by" integer,
  "cover_url" text,
  "default_meeting_link" text,
  "booking_window_settings" text,
  "extended_profile" text,
  "created_at" timestamp,
  "updated_at" timestamp
);

CREATE TABLE "mentee_profiles" (
  "member_id" integer PRIMARY KEY,
  "mentoring_goal" text,
  "major" text,
  "academic_year" text,
  "interests" text,
  "is_active" boolean NOT NULL DEFAULT true,
  "created_at" timestamp,
  "updated_at" timestamp
);

CREATE TABLE "mentor_expertise" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "mentor_member_id" integer,
  "topic" text,
  "years_experience" integer,
  "description" text,
  "category" text,
  "tag" text
);

CREATE TABLE "mentor_availabilities" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "mentor_member_id" integer,
  "start_time" timestamp,
  "end_time" timestamp,
  "status" text DEFAULT 'AVAILABLE'
);

CREATE TABLE "mentorship_sessions" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "availability_id" integer,
  "mentee_member_id" integer,
  "status" text,
  "booking_note" text,
  "meeting_link" text,
  "session_type" text,
  "introduction" text,
  "description" text,
  "cv_url" text,
  "cancel_reason" text,
  "created_at" timestamp
);

CREATE TABLE "mentorship_reports" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "session_id" integer,
  "reporter_member_id" integer,
  "reported_member_id" integer,
  "reason_category" text,
  "description" text,
  "status" text,
  "created_at" timestamp
);

CREATE TABLE "session_feedbacks" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "session_id" integer,
  "mentee_member_id" integer,
  "rating" integer,
  "comment" text,
  "is_public" boolean,
  "created_at" timestamp
);

CREATE TABLE "news" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "organization_id" integer,
  "author_member_id" integer,
  "title" text,
  "slug" text,
  "content" text,
  "thumbnail_url" text,
  "topic" text,
  "url" text,
  "is_hidden" boolean,
  "published_at" timestamp
);

CREATE TABLE "alumni_posts" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "organization_id" integer,
  "author_member_id" integer,
  "title" text,
  "slug" text,
  "content" text,
  "thumbnail_url" text,
  "topic" text,
  "url" text,
  "is_hidden" boolean,
  "published_at" timestamp
);

CREATE TABLE "saved_items" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "member_id" integer,
  "item_type" text,
  "item_id" integer,
  "note" text,
  "saved_at" timestamp
);

CREATE TABLE "achievements" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "member_id" integer,
  "title" text,
  "description" text,
  "image_url" text,
  "awarded_date" date,
  "topic" text,
  "status" text
);

CREATE TABLE "jobs" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "organization_id" integer,
  "poster_member_id" integer,
  "is_referral" boolean DEFAULT false,
  "type" text,
  "title" text,
  "company_name" text,
  "location" text,
  "salary_range" text,
  "description" text,
  "how_to_apply" text,
  "deadline" date,
  "is_active" boolean,
  "created_at" timestamp
);

CREATE TABLE "learning_resources" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "organization_id" integer,
  "uploader_member_id" integer,
  "title" text,
  "type" text,
  "link_url" text,
  "description" text,
  "created_at" timestamp
);

-- Thong tin cua quy
CREATE TABLE "funds" (
  "id" BIGSERIAL PRIMARY KEY,
  "organization_id" integer,
  --"manager_member_id" integer,
  "manager_name" text,  -- old: manager_member_id, 
  -- but in the figma file, i see the text field input for this, 
  -- and it is more concise as the manager may not be an alumni 
  "name" text,
  "logo_url" text,
  "fund_receiving_info_id" integer, -- khoa ngoai den fund_receiving_infos
  "description_short" text, -- dung de hien thi khi xem list view
  "description_full" text, -- dung de hien thi khi xem detail view
  "target_amount" decimal,
  "current_amount" decimal,
  "time_started" timestamp,
  "donor_count" integer DEFAULT 0, -- so luong donate, phuc vu frontend
  "status_id" integer,  -- khoa ngoai den fund_statuses
  "topic" text,
  "time_ended" timestamp
);

CREATE TABLE "fund_statuses" ( -- force to have as admin can add new status, mac dinh la co QUAN TRONG, VUNG SAU VUNG XA
  "id" SERIAL PRIMARY KEY,
  "name" text
);

CREATE TABLE "fund_receiving_infos" (
  "id" BIGSERIAL PRIMARY KEY,
  --"type" text,
  "account_number" text,
  "account_name" text,
  "bank_name" text, -- ma code dua tren payos
  -- "qr_code_url" text, generate QR dong nen se khong can cai nay
  "is_active" boolean  -- trang thai dang ki tren payos, neu chua dang ki thi = false
);

CREATE TABLE "fund_donations" (
  "id" BIGSERIAL PRIMARY KEY,
  "fund_id" integer,
  "donor_member_id" integer, -- nullable as if the donate person is guest
  "donor_name" text,
  "amount" decimal NOT NULL,
  "address" text,
  "phone" text,
  "email" text,
  "message" text,
  "status" text, -- enum: PENDING, SUCCESS, FAILED
  "created_at" timestamp
);

CREATE TABLE "notifications" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "member_id" integer,
  "title" text,
  "message" text,
  "is_read" boolean,
  "link" text,
  "created_at" timestamp
);

CREATE TABLE "school_feedbacks" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "organization_id" integer NOT NULL,
  "full_name" text,
  "phone" text,
  "email" text,
  "subject" text,
  "ai_summary" text,
  "content" text NOT NULL,
  "created_at" timestamp DEFAULT CURRENT_TIMESTAMP,
  "is_read" boolean DEFAULT false
);

CREATE TABLE "user_login_histories" (
  "id" BIGSERIAL PRIMARY KEY,
  "user_id" integer NOT NULL,
  "login_at" timestamp DEFAULT CURRENT_TIMESTAMP,
  "login_method" text,
  "login_ip" text,
  "user_agent" text
);

CREATE TABLE "user_notification_settings" (
  "user_id" integer PRIMARY KEY,
  "email_enabled" boolean DEFAULT true,
  "push_enabled" boolean DEFAULT true,
  "event_reminder_enabled" boolean DEFAULT true,
  "news_enabled" boolean DEFAULT true,
  "forum_reply_enabled" boolean DEFAULT true,
  "updated_at" timestamp DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE "forum_categories" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "parent_id" integer DEFAULT NULL,
  "organization_id" integer,
  "name" text,
  "description" text,
  "created_at" timestamp,
  "updated_at" timestamp
);

CREATE TABLE "forum_topics" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "organization_id" integer,
  "title" text,
  "created_by_member_id" integer,
  "category_id" integer, 
  "view_count" integer DEFAULT 0,
  "is_locked" boolean DEFAULT false,
  "created_at" timestamp,
  "updated_at" timestamp
);

CREATE TABLE "forum_posts" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "topic_id" integer,
  "author_member_id" integer,
  "content" text,
  "answer_to_post_id" integer,
  "ai_tag" text,
  "is_banned" boolean DEFAULT false,
  "is_hidden" boolean DEFAULT false,
  "created_at" timestamp,
  "updated_at" timestamp
);

CREATE TABLE "forum_post_reports" (
  "id" BIGSERIAL PRIMARY KEY,
  "post_id" integer NOT NULL,
  "reporter_member_id" integer NOT NULL,
  "reason" text,
  "description" text,
  "status" text DEFAULT 'PENDING',
  "reviewed_by_user_id" integer,
  "review_note" text,
  "created_at" timestamp DEFAULT CURRENT_TIMESTAMP,
  "updated_at" timestamp DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE "forum_post_reactions" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "post_id" integer NOT NULL,
  "member_id" integer NOT NULL,
  "created_at" timestamp DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE "forum_topic_subscriptions" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "topic_id" integer NOT NULL,
  "member_id" integer NOT NULL,
  "last_read_at" timestamp DEFAULT CURRENT_TIMESTAMP,
  "last_notified_at" timestamp DEFAULT CURRENT_TIMESTAMP,
  "created_at" timestamp DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE "forum_polls" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "topic_id" integer,
  "organization_id" integer,
  "created_by_member_id" integer,
  "title" text NOT NULL,
  "description" text,
  "allow_multiple_votes" boolean DEFAULT false,
  "is_active" boolean DEFAULT true,
  "created_at" timestamp DEFAULT CURRENT_TIMESTAMP,
  "updated_at" timestamp DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE "admin_audit_logs" (
  "id" BIGSERIAL PRIMARY KEY,
  "admin_user_id" integer NOT NULL,
  "target_user_id" integer,
  "action" text NOT NULL,
  "resource_type" text NOT NULL,
  "resource_id" text,
  "before_data" jsonb,
  "after_data" jsonb,
  "metadata" jsonb,
  "created_at" timestamp DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE "forum_poll_options" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "poll_id" integer NOT NULL,
  "option_text" text NOT NULL,
  "vote_count" integer DEFAULT 0,
  "created_at" timestamp DEFAULT CURRENT_TIMESTAMP,
  "updated_at" timestamp DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE "forum_poll_votes" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "poll_id" integer NOT NULL,
  "poll_option_id" integer NOT NULL,
  "member_id" integer NOT NULL,
  "created_at" timestamp DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE "chat_groups" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "type" text NOT NULL,                -- 'PRIVATE' hoặc 'GROUP'
  "title" text,                        -- tên group (PRIVATE group thi gia tri nay la null)
  "created_by" integer NOT NULL,
  "created_at" timestamp DEFAULT CURRENT_TIMESTAMP,
  "updated_at" timestamp DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE "chat_group_members" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "group_id" integer NOT NULL,
  "member_id" integer NOT NULL,
  "role" text DEFAULT 'MEMBER',     -- 'OWNER' / 'MEMBER'
  "joined_at" timestamp DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE "chat_messages" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "group_id" integer NOT NULL,
  "sender_member_id" integer NOT NULL,
  "content" text NOT NULL, -- an url
  "message_type" text DEFAULT 'TEXT', -- TEXT / IMAGE / FILE...
  "metadata" JSONB,                       -- optional, lưu info file, reaction...
  "created_at" timestamp DEFAULT CURRENT_TIMESTAMP,
  "edited_at" timestamp,
  "deleted_at" timestamp
);

CREATE TABLE "chat_conversation_requests" (
  "id" BIGSERIAL PRIMARY KEY,

  "member_low_id" integer NOT NULL,
  "member_high_id" integer NOT NULL,

  "requester_member_id" integer NOT NULL,

  "target_member_id" integer NOT NULL,

  "chat_group_id" integer UNIQUE NOT NULL,

  "last_request_message_id" integer NOT NULL,

  "cooldown_until" timestamp,

  "status" text NOT NULL DEFAULT 'PENDING', -- PENDING, ACCEPTED, REJECTED

  "created_at" timestamp DEFAULT CURRENT_TIMESTAMP,
  "updated_at" timestamp DEFAULT CURRENT_TIMESTAMP
);

CREATE UNIQUE INDEX ON "chat_conversation_requests" ("member_low_id", "member_high_id");

CREATE TABLE "user_blocks" (
  "id" BIGSERIAL PRIMARY KEY,
  "blocker_member_id" integer NOT NULL,
  "blocked_member_id" integer NOT NULL,
  "created_at" timestamp DEFAULT CURRENT_TIMESTAMP
);

CREATE UNIQUE INDEX ON "user_blocks" ("blocker_member_id", "blocked_member_id");

CREATE UNIQUE INDEX ON "chat_group_members" ("group_id", "member_id");

CREATE UNIQUE INDEX ON "peer_verifications" ("target_member_id", "verifier_member_id");

CREATE UNIQUE INDEX ON "forum_post_reactions" ("post_id", "member_id");

CREATE UNIQUE INDEX ON "forum_topic_subscriptions" ("topic_id", "member_id");

CREATE UNIQUE INDEX ON "forum_poll_votes" ("poll_id", "member_id");

CREATE UNIQUE INDEX ON "event_interests" ("event_id", "member_id");

CREATE INDEX ON "event_tickets" ("event_id", "status");

CREATE INDEX ON "event_tickets" ("member_id");

CREATE UNIQUE INDEX ON "event_invitations" ("token");

CREATE INDEX ON "event_invitations" ("event_id", "status");

CREATE INDEX ON "event_email_logs" ("event_id", "sent_at" DESC);

CREATE UNIQUE INDEX ON "saved_items" ("member_id", "item_type", "item_id");

ALTER TABLE "global_profiles" ADD FOREIGN KEY ("user_id") REFERENCES "users" ("id");

ALTER TABLE "organization_members" ADD FOREIGN KEY ("organization_id") REFERENCES "organizations" ("id");

ALTER TABLE "organization_members" ADD FOREIGN KEY ("user_id") REFERENCES "users" ("id");

ALTER TABLE "peer_verifications" ADD FOREIGN KEY ("target_member_id") REFERENCES "organization_members" ("user_id");

ALTER TABLE "peer_verifications" ADD FOREIGN KEY ("verifier_member_id") REFERENCES "organization_members" ("user_id");

ALTER TABLE "verification_requests" ADD FOREIGN KEY ("member_id") REFERENCES "organization_members" ("user_id");

ALTER TABLE "verification_requests" ADD FOREIGN KEY ("reviewed_by_member_id") REFERENCES "organization_members" ("user_id");

ALTER TABLE "events" ADD FOREIGN KEY ("organization_id") REFERENCES "organizations" ("id");

ALTER TABLE "events" ADD FOREIGN KEY ("creator_member_id") REFERENCES "organization_members" ("user_id");

ALTER TABLE "event_interests" ADD FOREIGN KEY ("event_id") REFERENCES "events" ("id");

ALTER TABLE "event_interests" ADD FOREIGN KEY ("member_id") REFERENCES "organization_members" ("user_id");

ALTER TABLE "event_tickets" ADD FOREIGN KEY ("event_id") REFERENCES "events" ("id");

ALTER TABLE "event_tickets" ADD FOREIGN KEY ("member_id") REFERENCES "organization_members" ("user_id");

ALTER TABLE "event_tickets" ADD FOREIGN KEY ("reviewed_by") REFERENCES "organization_members" ("user_id");

ALTER TABLE "event_invitations" ADD FOREIGN KEY ("event_id") REFERENCES "events" ("id");

ALTER TABLE "event_invitations" ADD FOREIGN KEY ("member_id") REFERENCES "organization_members" ("user_id");

ALTER TABLE "event_invitations" ADD FOREIGN KEY ("invited_by") REFERENCES "organization_members" ("user_id");

ALTER TABLE "event_email_logs" ADD FOREIGN KEY ("event_id") REFERENCES "events" ("id");

ALTER TABLE "event_email_logs" ADD FOREIGN KEY ("sent_by") REFERENCES "organization_members" ("user_id");

ALTER TABLE "mentor_profiles" ADD FOREIGN KEY ("member_id") REFERENCES "organization_members" ("user_id");

ALTER TABLE "mentee_profiles" ADD FOREIGN KEY ("member_id") REFERENCES "organization_members" ("user_id");

ALTER TABLE "mentor_expertise" ADD FOREIGN KEY ("mentor_member_id") REFERENCES "mentor_profiles" ("member_id");

ALTER TABLE "mentor_availabilities" ADD FOREIGN KEY ("mentor_member_id") REFERENCES "mentor_profiles" ("member_id");

ALTER TABLE "mentorship_sessions" ADD FOREIGN KEY ("availability_id") REFERENCES "mentor_availabilities" ("id");

ALTER TABLE "mentorship_sessions" ADD FOREIGN KEY ("mentee_member_id") REFERENCES "organization_members" ("user_id");

ALTER TABLE "mentorship_reports" ADD FOREIGN KEY ("session_id") REFERENCES "mentorship_sessions" ("id");

ALTER TABLE "mentorship_reports" ADD FOREIGN KEY ("reporter_member_id") REFERENCES "organization_members" ("user_id");

ALTER TABLE "mentorship_reports" ADD FOREIGN KEY ("reported_member_id") REFERENCES "organization_members" ("user_id");

ALTER TABLE "session_feedbacks" ADD FOREIGN KEY ("session_id") REFERENCES "mentorship_sessions" ("id");

ALTER TABLE "session_feedbacks" ADD FOREIGN KEY ("mentee_member_id") REFERENCES "organization_members" ("user_id");

ALTER TABLE "news" ADD FOREIGN KEY ("organization_id") REFERENCES "organizations" ("id");

ALTER TABLE "news" ADD FOREIGN KEY ("author_member_id") REFERENCES "organization_members" ("user_id");

ALTER TABLE "saved_items" ADD FOREIGN KEY ("member_id") REFERENCES "organization_members" ("user_id");

ALTER TABLE "achievements" ADD FOREIGN KEY ("member_id") REFERENCES "organization_members" ("user_id");

ALTER TABLE "jobs" ADD FOREIGN KEY ("organization_id") REFERENCES "organizations" ("id");

ALTER TABLE "jobs" ADD FOREIGN KEY ("poster_member_id") REFERENCES "organization_members" ("user_id");

ALTER TABLE "learning_resources" ADD FOREIGN KEY ("organization_id") REFERENCES "organizations" ("id");

ALTER TABLE "learning_resources" ADD FOREIGN KEY ("uploader_member_id") REFERENCES "organization_members" ("user_id");

ALTER TABLE "funds" ADD FOREIGN KEY ("organization_id") REFERENCES "organizations" ("id");

ALTER TABLE "fund_donations" ADD FOREIGN KEY ("fund_id") REFERENCES "funds" ("id");

ALTER TABLE "funds" ADD FOREIGN KEY ("status_id") REFERENCES "fund_statuses" ("id");

ALTER TABLE "fund_receiving_infos" ADD CONSTRAINT "uk_fund_receiving_infos_bank_account"
UNIQUE ("bank_name", "account_number");

ALTER TABLE "notifications" ADD FOREIGN KEY ("member_id") REFERENCES "organization_members" ("user_id");

ALTER TABLE "school_feedbacks" ADD FOREIGN KEY ("organization_id") REFERENCES "organizations" ("id");

ALTER TABLE "user_login_histories" ADD FOREIGN KEY ("user_id") REFERENCES "users" ("id");

ALTER TABLE "user_notification_settings" ADD FOREIGN KEY ("user_id") REFERENCES "users" ("id");

ALTER TABLE "forum_topics" ADD FOREIGN KEY ("organization_id") REFERENCES "organizations" ("id");

ALTER TABLE "forum_topics" ADD FOREIGN KEY ("created_by_member_id") REFERENCES "organization_members" ("user_id");

ALTER TABLE "forum_posts" ADD FOREIGN KEY ("topic_id") REFERENCES "forum_topics" ("id");

ALTER TABLE "forum_posts" ADD FOREIGN KEY ("author_member_id") REFERENCES "organization_members" ("user_id");

ALTER TABLE "forum_posts" ADD FOREIGN KEY ("answer_to_post_id") REFERENCES "forum_posts" ("id");

ALTER TABLE "forum_post_reports" ADD FOREIGN KEY ("post_id") REFERENCES "forum_posts" ("id");

ALTER TABLE "forum_post_reports" ADD FOREIGN KEY ("reporter_member_id") REFERENCES "organization_members" ("user_id");

ALTER TABLE "forum_post_reports" ADD FOREIGN KEY ("reviewed_by_user_id") REFERENCES "users" ("id");

ALTER TABLE "forum_post_reactions" ADD FOREIGN KEY ("post_id") REFERENCES "forum_posts" ("id");

ALTER TABLE "forum_post_reactions" ADD FOREIGN KEY ("member_id") REFERENCES "organization_members" ("user_id");

ALTER TABLE "forum_topic_subscriptions" ADD FOREIGN KEY ("topic_id") REFERENCES "forum_topics" ("id");

ALTER TABLE "forum_topic_subscriptions" ADD FOREIGN KEY ("member_id") REFERENCES "organization_members" ("user_id");

ALTER TABLE "forum_polls" ADD FOREIGN KEY ("topic_id") REFERENCES "forum_topics" ("id");

ALTER TABLE "forum_polls" ADD FOREIGN KEY ("organization_id") REFERENCES "organizations" ("id");

ALTER TABLE "forum_polls" ADD FOREIGN KEY ("created_by_member_id") REFERENCES "organization_members" ("user_id");

ALTER TABLE "forum_poll_options" ADD FOREIGN KEY ("poll_id") REFERENCES "forum_polls" ("id");

ALTER TABLE "forum_poll_votes" ADD FOREIGN KEY ("poll_id") REFERENCES "forum_polls" ("id");

ALTER TABLE "forum_poll_votes" ADD FOREIGN KEY ("poll_option_id") REFERENCES "forum_poll_options" ("id");

ALTER TABLE "forum_poll_votes" ADD FOREIGN KEY ("member_id") REFERENCES "organization_members" ("user_id");

ALTER TABLE "user_blocks" ADD FOREIGN KEY ("blocker_member_id") REFERENCES "organization_members" ("user_id");

ALTER TABLE "user_blocks" ADD FOREIGN KEY ("blocked_member_id") REFERENCES "organization_members" ("user_id");

ALTER TABLE "admin_audit_logs" ADD FOREIGN KEY ("admin_user_id") REFERENCES "users" ("id");

ALTER TABLE "admin_audit_logs" ADD FOREIGN KEY ("target_user_id") REFERENCES "users" ("id");

ALTER TABLE "forum_categories" ADD FOREIGN KEY ("organization_id") REFERENCES "organizations" ("id");

ALTER TABLE "forum_topics" ADD FOREIGN KEY ("category_id") REFERENCES "forum_categories" ("id");

CREATE INDEX ON "user_login_histories" ("user_id", "login_at" DESC);

CREATE INDEX ON "forum_post_reports" ("status", "created_at" DESC);

CREATE INDEX ON "admin_audit_logs" ("target_user_id", "created_at" DESC);

CREATE INDEX ON "school_feedbacks" ("organization_id", "is_read", "created_at" DESC);

CREATE INDEX ON "forum_posts" ("topic_id", "created_at" DESC);

CREATE INDEX ON "forum_topic_subscriptions" ("topic_id", "member_id", "last_read_at", "last_notified_at");

