create table users
(
    id                   integer generated by default as identity
        primary key,
    email                text
        unique,
    password_hash        text,
    status               text,
    role                 text,
    avatar_url           text,
    cover_url            text,
    created_at           timestamp default CURRENT_TIMESTAMP,
    updated_at           timestamp default CURRENT_TIMESTAMP,
    full_name            text,
    phone                text,
    bio                  text,
    dob                  date,
    gender               text,
    current_job_title    text,
    current_company      text,
    links                jsonb,
    settings             jsonb,
    must_change_password boolean   default false not null
);

alter table users
    owner to postgres;

create index idx_users_email_trgm
    on users using gin (email gin_trgm_ops);

create index idx_users_status
    on users (status);

create index idx_users_role
    on users (role);

create index idx_users_name_trgm
    on users using gin (full_name gin_trgm_ops);

create table organizations
(
    id              integer generated by default as identity
        primary key,
    name            text,
    slug            text
        unique,
    logo_url        text,
    brand_config    jsonb,
    features_config jsonb,
    programs        jsonb,
    majors          jsonb,
    status          text      default 'ACTIVE'::text,
    created_at      timestamp default CURRENT_TIMESTAMP,
    updated_at      timestamp default CURRENT_TIMESTAMP,
    contact_phone   text,
    contact_email   text,
    department_name text
);

alter table organizations
    owner to postgres;

create table organization_introductions
(
    id                   integer generated by default as identity
        primary key,
    orga_id              integer
        unique
        references organizations
            on delete cascade,
    content              text,
    vision               text,
    mission              text,
    core_values          text,
    image_urls           text,
    banner_url           text,
    leaders              jsonb,
    team_members         jsonb,
    leaders_content      text,
    team_members_content text,
    updated_at           timestamp default CURRENT_TIMESTAMP
);

alter table organization_introductions
    owner to postgres;

create table organization_members
(
    id                  integer generated by default as identity
        primary key,
    organization_id     integer
        references organizations,
    user_id             integer
        references users,
    student_id          text,
    started_year        jsonb,
    graduated_year      jsonb,
    graduation_status   jsonb,
    program             jsonb,
    major               jsonb,
    faculty             jsonb,
    department          jsonb,
    verification_level  integer   default 0,
    is_trusted_verifier boolean   default false,
    status              text      default 'ACTIVE'::text,
    created_at          timestamp default CURRENT_TIMESTAMP,
    updated_at          timestamp default CURRENT_TIMESTAMP,
    constraint uk_organization_members_student_id
        unique (organization_id, student_id),
    constraint uk_organization_members_org_user
        unique (organization_id, user_id)
);

alter table organization_members
    owner to postgres;

create index idx_organization_members_program_gin
    on organization_members using gin (program);

create index idx_organization_members_major_gin
    on organization_members using gin (major);

create table peer_verifications
(
    id                 integer generated by default as identity
        primary key,
    target_member_id   integer,
    verifier_member_id integer,
    status             text      default 'PENDING'::text,
    created_at         timestamp default CURRENT_TIMESTAMP,
    organization_id    integer
        constraint fk_peer_verifications_organization
            references organizations
);

alter table peer_verifications
    owner to postgres;

create unique index uk_peer_verifications_org_target_verifier
    on peer_verifications (organization_id, target_member_id, verifier_member_id);

create index idx_peer_verifications_org
    on peer_verifications (organization_id);

create table verification_requests
(
    id                    integer generated by default as identity
        primary key,
    member_id             integer,
    document_url          text,
    document_type         text,
    ai_summary            text,
    status                text,
    admin_note            text,
    reviewed_by_member_id integer,
    created_at            timestamp default CURRENT_TIMESTAMP,
    updated_at            timestamp default CURRENT_TIMESTAMP,
    organization_id       integer
        constraint fk_verification_requests_organization
            references organizations
);

alter table verification_requests
    owner to postgres;

create index idx_verification_status
    on verification_requests (status);

create index idx_verification_requests_org
    on verification_requests (organization_id);

create table events
(
    id                    integer generated by default as identity
        primary key,
    organization_id       integer
        references organizations,
    creator_member_id     integer
        references organization_members (user_id),
    title                 text,
    description           text,
    banner_url            text,
    location              text,
    start_time            timestamp,
    end_time              timestamp,
    registration_start_at timestamp,
    registration_end_at   timestamp,
    max_capacity          integer,
    interested_count      integer   default 0,
    topic                 text,
    is_published          boolean   default false,
    created_at            timestamp,
    updated_at            timestamp default CURRENT_TIMESTAMP,
    requires_check_in     boolean   default false not null
);

alter table events
    owner to postgres;

create table event_interests
(
    id         integer generated by default as identity
        primary key,
    event_id   integer
        references events,
    member_id  integer
        references organization_members (user_id),
    created_at timestamp
);

alter table event_interests
    owner to postgres;

create unique index event_interests_event_id_member_id_idx
    on event_interests (event_id, member_id);

create table event_tickets
(
    id                   integer generated by default as identity
        primary key,
    event_id             integer
        references events,
    member_id            integer
        references organization_members (user_id),
    guest_name           text,
    guest_email          text,
    guest_phone          text,
    ticket_code          text
        unique,
    status               text      default 'ISSUED'::text not null,
    registered_at        timestamp default CURRENT_TIMESTAMP,
    checked_in_at        timestamp,
    reviewed_by          integer
        references organization_members (user_id),
    reviewed_at          timestamp,
    reject_reason        text,
    registration_answers text,
    cancel_reason        text
);

alter table event_tickets
    owner to postgres;

create index event_tickets_event_id_status_idx
    on event_tickets (event_id, status);

create index event_tickets_member_id_idx
    on event_tickets (member_id);

create table event_questions
(
    id          integer generated by default as identity
        primary key,
    event_id    integer                 not null,
    type        text                    not null,
    label       text                    not null,
    options     text,
    required    boolean   default false not null,
    order_index integer   default 0     not null,
    created_at  timestamp default CURRENT_TIMESTAMP
);

alter table event_questions
    owner to postgres;

create index idx_event_questions_event
    on event_questions (event_id);

create table event_invitations
(
    id           integer generated by default as identity
        primary key,
    event_id     integer                           not null
        references events,
    member_id    integer
        references organization_members (user_id),
    email        text                              not null,
    token        text                              not null
        unique,
    status       text      default 'PENDING'::text not null,
    invited_by   integer                           not null
        references organization_members (user_id),
    invited_at   timestamp default CURRENT_TIMESTAMP,
    confirmed_at timestamp,
    expires_at   timestamp
);

alter table event_invitations
    owner to postgres;

create unique index event_invitations_token_idx
    on event_invitations (token);

create index event_invitations_event_id_status_idx
    on event_invitations (event_id, status);

create table event_email_logs
(
    id              integer generated by default as identity
        primary key,
    event_id        integer not null
        references events,
    sent_by         integer not null
        references organization_members (user_id),
    template_name   text,
    subject         text,
    recipient_count integer   default 0,
    sent_at         timestamp default CURRENT_TIMESTAMP
);

alter table event_email_logs
    owner to postgres;

create index event_email_logs_event_id_sent_at_idx
    on event_email_logs (event_id asc, sent_at desc);

create table mentor_profiles
(
    member_id               integer                       not null
        primary key
        references organization_members (user_id),
    current_job_title       text,
    current_company         text,
    bio                     text,
    rating_avg              numeric default 0,
    total_sessions          integer default 0,
    status                  text    default 'DRAFT'::text not null
        constraint mentor_profiles_status_check
            check (status = ANY
                   (ARRAY ['DRAFT'::text, 'PENDING'::text, 'APPROVED'::text, 'REJECTED'::text, 'NEED_UPDATE'::text])),
    review_note             text,
    reviewed_at             timestamp,
    reviewed_by             integer,
    default_meeting_link    text,
    booking_window_settings text,
    extended_profile        text,
    created_at              timestamp,
    updated_at              timestamp
);

alter table mentor_profiles
    owner to postgres;

create table mentee_profiles
(
    member_id      integer              not null
        primary key
        references organization_members (user_id),
    mentoring_goal text,
    major          text,
    academic_year  text,
    interests      text,
    is_active      boolean default true not null,
    created_at     timestamp,
    updated_at     timestamp
);

alter table mentee_profiles
    owner to postgres;

create table mentor_expertise
(
    id               integer generated by default as identity
        primary key,
    mentor_member_id integer
        references mentor_profiles,
    topic            text,
    years_experience integer,
    description      text,
    category         text,
    tag              text
);

alter table mentor_expertise
    owner to postgres;

create table mentor_availabilities
(
    id               integer generated by default as identity
        primary key,
    mentor_member_id integer
        references mentor_profiles,
    start_time       timestamp,
    end_time         timestamp,
    status           text default 'AVAILABLE'::text
);

alter table mentor_availabilities
    owner to postgres;

create table skills
(
    id         integer generated by default as identity
        primary key,
    name       text not null,
    created_at timestamp default CURRENT_TIMESTAMP not null
);

alter table skills
    owner to postgres;

create unique index idx_skills_name_lower
    on skills (lower(name));

create table mentor_skills
(
    id               integer generated by default as identity
        primary key,
    mentor_member_id integer not null
        references mentor_profiles,
    skill_id         integer not null
        references skills,
    display_order    integer default 0 not null,
    unique (mentor_member_id, skill_id)
);

alter table mentor_skills
    owner to postgres;

create table mentorship_sessions
(
    id                       integer generated by default as identity
        primary key,
    availability_id          integer
        references mentor_availabilities,
    mentee_member_id         integer
        references organization_members (user_id),
    status                   text,
    booking_note             text,
    meeting_link             text,
    session_type             text,
    introduction             text,
    description              text,
    cv_url                   text,
    cancel_reason            text,
    proposed_start_time      timestamp,
    proposed_end_time        timestamp,
    mentor_joined_at         timestamp,
    mentee_joined_at         timestamp,
    started_at               timestamp,
    ended_at                 timestamp,
    meeting_link_reminded_at timestamp,
    created_at               timestamp
);

alter table mentorship_sessions
    owner to postgres;

create index idx_sessions_status
    on mentorship_sessions (status);

create table mentorship_reports
(
    id                 integer generated by default as identity
        primary key,
    session_id         integer
        references mentorship_sessions,
    reporter_member_id integer
        references organization_members (user_id),
    reported_member_id integer
        references organization_members (user_id),
    reason_category    text,
    description        text,
    status             text,
    created_at         timestamp
);

alter table mentorship_reports
    owner to postgres;

create table session_feedbacks
(
    id               integer generated by default as identity
        primary key,
    session_id       integer
        references mentorship_sessions,
    mentee_member_id integer
        references organization_members (user_id),
    rating           integer,
    comment          text,
    is_public        boolean,
    created_at       timestamp
);

alter table session_feedbacks
    owner to postgres;

create table news
(
    id               integer generated by default as identity
        primary key,
    organization_id  integer
        references organizations,
    author_member_id integer
        references organization_members (user_id),
    title            text,
    slug             text,
    content          text,
    thumbnail_url    text,
    topic            text,
    url              text,
    is_hidden        boolean,
    published_at     timestamp,
    created_at       timestamp default CURRENT_TIMESTAMP,
    updated_at       timestamp default CURRENT_TIMESTAMP
);

alter table news
    owner to postgres;

create table alumni_posts
(
    id               integer generated by default as identity
        primary key,
    organization_id  integer,
    author_member_id integer,
    title            text,
    slug             text,
    content          text,
    thumbnail_url    text,
    topic            text,
    url              text,
    is_hidden        boolean,
    published_at     timestamp,
    created_at       timestamp default CURRENT_TIMESTAMP,
    updated_at       timestamp default CURRENT_TIMESTAMP
);

alter table alumni_posts
    owner to postgres;

create table saved_items
(
    id        integer generated by default as identity
        primary key,
    member_id integer
        references organization_members (user_id),
    item_type text,
    item_id   integer,
    note      text,
    saved_at  timestamp
);

alter table saved_items
    owner to postgres;

create unique index saved_items_member_id_item_type_item_id_idx
    on saved_items (member_id, item_type, item_id);

create table achievements
(
    id           integer generated by default as identity
        primary key,
    member_id    integer
        references organization_members (user_id),
    title        text,
    description  text,
    image_url    text,
    awarded_date date,
    topic        text,
    status       text,
    created_at   timestamp default CURRENT_TIMESTAMP,
    updated_at   timestamp default CURRENT_TIMESTAMP
);

alter table achievements
    owner to postgres;

create table jobs
(
    id               integer generated by default as identity
        primary key,
    organization_id  integer
        references organizations,
    poster_member_id integer
        references organization_members (user_id),
    is_referral      boolean   default false,
    type             text,
    title            text,
    company_name     text,
    location         text,
    salary_range     text,
    description      text,
    how_to_apply     text,
    deadline         date,
    is_active        boolean,
    created_at       timestamp,
    updated_at       timestamp default CURRENT_TIMESTAMP
);

alter table jobs
    owner to postgres;

create table learning_resources
(
    id                 integer generated by default as identity
        primary key,
    organization_id    integer
        references organizations,
    uploader_member_id integer
        references organization_members (user_id),
    title              text,
    type               text,
    link_url           text,
    description        text,
    created_at         timestamp,
    updated_at         timestamp default CURRENT_TIMESTAMP
);

alter table learning_resources
    owner to postgres;

create table funds
(
    id                     bigserial
        primary key,
    organization_id        integer
        references organizations,
    manager_name           text,
    name                   text,
    logo_url               text,
    fund_receiving_info_id integer,
    description_short      text,
    description_full       text,
    target_amount          numeric,
    current_amount         numeric,
    time_started           timestamp,
    donor_count            integer   default 0,
    topic                  text,
    time_ended             timestamp,
    created_at             timestamp default CURRENT_TIMESTAMP,
    updated_at             timestamp default CURRENT_TIMESTAMP,
    manager_email          text not null,
    fund_document_url      text
);

alter table funds
    owner to postgres;

create table fund_receiving_infos
(
    id             bigserial
        primary key,
    account_number text,
    account_name   text,
    bank_name      text,
    is_active      boolean,
    constraint uk_fund_receiving_infos_bank_account
        unique (bank_name, account_number)
);

alter table fund_receiving_infos
    owner to postgres;

create table fund_donations
(
    id              bigserial
        primary key,
    fund_id         integer
        references funds,
    donor_member_id integer,
    donor_name      text,
    amount          numeric not null,
    address         text,
    phone           text,
    email           text,
    message         text,
    status          text,
    created_at      timestamp
);

alter table fund_donations
    owner to postgres;

create table notifications
(
    id         integer generated by default as identity
        primary key,
    member_id  integer
        references organization_members (user_id),
    title      text,
    message    text,
    is_read    boolean,
    link       text,
    created_at timestamp
);

alter table notifications
    owner to postgres;

create index idx_notifications_member
    on notifications (member_id);

create table school_feedbacks
(
    id              integer generated by default as identity
        primary key,
    organization_id integer not null
        references organizations,
    full_name       text,
    phone           text,
    email           text,
    subject         text,
    ai_summary      text,
    content         text    not null,
    created_at      timestamp default CURRENT_TIMESTAMP,
    is_read         boolean   default false
);

alter table school_feedbacks
    owner to postgres;

create index school_feedbacks_organization_id_is_read_created_at_idx
    on school_feedbacks (organization_id asc, is_read asc, created_at desc);

create table user_login_histories
(
    id           bigserial
        primary key,
    user_id      integer not null
        references users,
    login_at     timestamp default CURRENT_TIMESTAMP,
    login_method text,
    login_ip     text,
    user_agent   text
);

alter table user_login_histories
    owner to postgres;

create index user_login_histories_user_id_login_at_idx
    on user_login_histories (user_id asc, login_at desc);

create table user_notification_settings
(
    user_id                integer not null
        primary key
        references users,
    email_enabled          boolean   default true,
    push_enabled           boolean   default true,
    event_reminder_enabled boolean   default true,
    news_enabled           boolean   default true,
    forum_reply_enabled    boolean   default true,
    updated_at             timestamp default CURRENT_TIMESTAMP
);

alter table user_notification_settings
    owner to postgres;

create table forum_categories
(
    id              integer generated by default as identity
        primary key,
    parent_id       integer,
    organization_id integer
        references organizations,
    name            text,
    description     text,
    created_at      timestamp,
    updated_at      timestamp,
    status          text default 'ACTIVE'::text
);

alter table forum_categories
    owner to postgres;

create table forum_topics
(
    id                   integer generated by default as identity
        primary key,
    organization_id      integer
        references organizations,
    title                text,
    created_by_member_id integer
        references organization_members (user_id),
    category_id          integer
        references forum_categories,
    view_count           integer default 0,
    created_at           timestamp,
    updated_at           timestamp,
    status               text    default 'ACTIVE'::text
);

alter table forum_topics
    owner to postgres;

create index idx_forum_topics_title_trgm
    on forum_topics using gin (title gin_trgm_ops);

create table forum_posts
(
    id                integer generated by default as identity
        primary key,
    topic_id          integer
        references forum_topics,
    author_member_id  integer
        references organization_members (user_id),
    content           text,
    answer_to_post_id integer
        references forum_posts,
    ai_tag            text,
    is_banned         boolean default false,
    is_hidden         boolean default false,
    created_at        timestamp,
    updated_at        timestamp
);

alter table forum_posts
    owner to postgres;

create index forum_posts_topic_id_created_at_idx
    on forum_posts (topic_id asc, created_at desc);

create index idx_forum_posts_content_trgm
    on forum_posts using gin (content gin_trgm_ops);

create table forum_post_reports
(
    id                  bigserial
        primary key,
    post_id             integer not null
        references forum_posts,
    reporter_member_id  integer not null
        references organization_members (user_id),
    reason              text,
    status              text      default 'PENDING'::text,
    reviewed_by_user_id integer
        references users,
    review_note         text,
    created_at          timestamp default CURRENT_TIMESTAMP,
    updated_at          timestamp default CURRENT_TIMESTAMP
);

alter table forum_post_reports
    owner to postgres;

create index forum_post_reports_status_created_at_idx
    on forum_post_reports (status asc, created_at desc);

create index forum_post_reports_post_id_idx
    on forum_post_reports (post_id);

create table forum_post_reactions
(
    id         integer generated by default as identity
        primary key,
    post_id    integer not null
        references forum_posts,
    member_id  integer not null
        references organization_members (user_id),
    created_at timestamp default CURRENT_TIMESTAMP
);

alter table forum_post_reactions
    owner to postgres;

create unique index forum_post_reactions_post_id_member_id_idx
    on forum_post_reactions (post_id, member_id);

create table forum_topic_subscriptions
(
    id               integer generated by default as identity
        primary key,
    topic_id         integer not null
        references forum_topics,
    member_id        integer not null
        references organization_members (user_id),
    last_read_at     timestamp default CURRENT_TIMESTAMP,
    last_notified_at timestamp default CURRENT_TIMESTAMP,
    created_at       timestamp default CURRENT_TIMESTAMP
);

alter table forum_topic_subscriptions
    owner to postgres;

create unique index forum_topic_subscriptions_topic_id_member_id_idx
    on forum_topic_subscriptions (topic_id, member_id);

create index forum_topic_subscriptions_topic_id_member_id_last_read_at_l_idx
    on forum_topic_subscriptions (topic_id, member_id, last_read_at, last_notified_at);

create table admin_audit_logs
(
    id             bigserial
        primary key,
    admin_user_id  integer not null
        references users,
    target_user_id integer
        references users,
    action         text    not null,
    resource_type  text    not null,
    resource_id    text,
    before_data    jsonb,
    after_data     jsonb,
    metadata       jsonb,
    created_at     timestamp default CURRENT_TIMESTAMP
);

alter table admin_audit_logs
    owner to postgres;

create index admin_audit_logs_target_user_id_created_at_idx
    on admin_audit_logs (target_user_id asc, created_at desc);

create table chat_groups
(
    id         integer generated by default as identity
        primary key,
    type       text    not null,
    title      text,
    created_by integer not null,
    created_at timestamp default CURRENT_TIMESTAMP,
    updated_at timestamp default CURRENT_TIMESTAMP
);

alter table chat_groups
    owner to postgres;

create table chat_group_members
(
    id        integer generated by default as identity
        primary key,
    group_id  integer not null,
    member_id integer not null,
    role      text      default 'MEMBER'::text,
    joined_at timestamp default CURRENT_TIMESTAMP
);

alter table chat_group_members
    owner to postgres;

create unique index chat_group_members_group_id_member_id_idx
    on chat_group_members (group_id, member_id);

create index chat_group_members_member_id_idx
    on chat_group_members (member_id);

create table chat_messages
(
    id               integer generated by default as identity
        primary key,
    group_id         integer not null,
    sender_member_id integer not null,
    content          text    not null,
    message_type     text      default 'TEXT'::text,
    metadata         jsonb,
    created_at       timestamp default CURRENT_TIMESTAMP,
    edited_at        timestamp,
    deleted_at       timestamp
);

alter table chat_messages
    owner to postgres;

create index chat_messages_group_id_created_at_idx
    on chat_messages (group_id asc, created_at desc);

create table chat_conversation_requests
(
    id                      bigserial
        primary key,
    member_low_id           integer                           not null,
    member_high_id          integer                           not null,
    requester_member_id     integer                           not null,
    target_member_id        integer                           not null,
    chat_group_id           integer                           not null
        unique,
    last_request_message_id integer                           not null,
    cooldown_until          timestamp,
    status                  text      default 'PENDING'::text not null,
    created_at              timestamp default CURRENT_TIMESTAMP,
    updated_at              timestamp default CURRENT_TIMESTAMP
);

alter table chat_conversation_requests
    owner to postgres;

create unique index chat_conversation_requests_member_low_id_member_high_id_idx
    on chat_conversation_requests (member_low_id, member_high_id);

create table user_blocks
(
    id                bigserial
        primary key,
    blocker_member_id integer not null
        references organization_members (user_id),
    blocked_member_id integer not null
        references organization_members (user_id),
    created_at        timestamp default CURRENT_TIMESTAMP
);

alter table user_blocks
    owner to postgres;

create unique index user_blocks_blocker_member_id_blocked_member_id_idx
    on user_blocks (blocker_member_id, blocked_member_id);

create table education_change_requests
(
    id                  integer generated by default as identity
        primary key,
    member_id           integer                           not null
        references organization_members
            on delete cascade,
    organization_id     integer                           not null,
    old_data            text,
    new_data            text                              not null,
    status              text      default 'PENDING'::text not null,
    admin_note          text,
    reviewed_by_user_id integer,
    created_at          timestamp default CURRENT_TIMESTAMP,
    reviewed_at         timestamp
);

alter table education_change_requests
    owner to postgres;

create index idx_education_change_requests_member
    on education_change_requests (member_id);

create index idx_education_change_requests_org_status
    on education_change_requests (organization_id, status);
